### ISSUE TITLE
[Bug]: Sync consumable used when browser closed before transaction is complete

### ISSUE THREAD

**Issue by neothon** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Neothon

### What happened?

If consumable is used. When the metamask popup is open and the game is closed, the consumable burns but isn't synced with the game server. 

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Related to #16
