### ISSUE TITLE
[Bug]: Able to gather Wood and Iron ore with gathering skill of 1

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

I'm able to gather _Wood_ and _Iron ore_ with a gathering skill of 1. Both of these items require a gathering skill of 5.

![image](https://user-images.githubusercontent.com/8630518/206370830-3b7566b0-9b60-4421-bc07-3b96869cc0e1.png)
![image](https://user-images.githubusercontent.com/8630518/206370900-3831e1ba-4269-43ac-9d3c-e154228ac58b.png)
![image](https://user-images.githubusercontent.com/8630518/206371066-ccf26dc9-cb84-44e8-8bea-de0d68401765.png)
![image](https://user-images.githubusercontent.com/8630518/206371203-2897c427-6cb7-4613-a582-c95bb0ff83c9.png)
![image](https://user-images.githubusercontent.com/8630518/206371258-0c574bd6-97f8-4bbd-8a99-bb3bef677294.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by samticketit** [comment]
This one is correct as you can still mine resources that are above your level

**Comment by sam-thewise** [comment]
This is intended functionality, you should be able to mine resources that are slightly higher level, since there are no level 1 resources.
