### ISSUE TITLE
[Bug]: End of fight info/recap

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

There is some issues with the End of fight information. Some information that appears in it are never shown before on the screen for the user.

1. Fight encounter + enemy quote doesn't show on on the screen until the fight ends. Only the end of fight one shows up.
![image](https://user-images.githubusercontent.com/8630518/206386315-173fcb75-616c-4ef0-8a19-e310a88897fc.png)

2. The End of fight information shows who got first hit because of their speed. If the enemy hits first, their first hit is recorded. If the player gets it, nothing is shown. I also think this information should get shown at the top of the screen in the notifications.

![image](https://user-images.githubusercontent.com/8630518/206386588-1afd085d-40dc-4181-bb7e-1f0682ab1458.png)

A nice and clean way to fix all of this would be to remove all those information and just keep the bottom 4 lines.
-You have slain X
-Kill quote
-Character XP
-DCAU/DCAR gains (if applicable)
![fight recap](https://user-images.githubusercontent.com/8630518/206386146-93d4a302-059f-4396-9c02-d845e6f046b8.jpg)

Sorry, poor quality audio.
https://youtu.be/LTYMz7qPcBI

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
I think the first part i.e. defeated enemy + quote is more like a winning quote after defeating the enemy. I agree with the rest of the bit though. Fixed those 👍🏼
