### ISSUE TITLE
[Bug]: Duplication frontend issues

### ISSUE THREAD

**Issue by Polypup** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

PolyPup

### What happened?

If a user attempts to duplicate items they will fail due to the signature not matching their items. We need to not allow them to earn more dcar if they have started a claim ect...

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
Fixed. User cannot search plains till previously started claim of tokens is completed
