### ISSUE TITLE
[Bug]:Coal disappear from wallet after forge.

### ISSUE THREAD

**Issue by WesToStakuj** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

friendly.fire#8915

### What happened?

It happend to me two or three days ago and again today.

1). I have big stack of coal in wallet and little corrupted ore what.
2). Go to forge to get some hardened corrupted bar.
3). Transaction approved. All corrupted ore is gone as should be. I have in stash hardened corrupted bar ready to be claim from there. I can see remaining coal in my wallet at this moment.
4). After couple minutes of game I check my wallet/inventory again and all coal is missing. Its not in stash not in inventory its not coming back after refresh or 2days span. 

![Screenshot 2022-12-10 081949](https://user-images.githubusercontent.com/119375694/206863961-1055f3b9-a793-430e-977c-8dd4d08c4dd6.png)
![Screenshot 2022-12-10 085215](https://user-images.githubusercontent.com/119375694/206863962-be0c8687-55d5-4788-ab17-d10fe6609c94.png)

Its winter I need that coal 

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed
