### ISSUE TITLE
[Bug]: Only single transaction at Forge 

### ISSUE THREAD

**Issue by WesToStakuj** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

friendly.fire#8915

### What happened?

1) I go to forge with my crafter and put coal and corrupted ore to the forge window
2) I smelt it and approve transaction and have new resources in stash as should be.
3) I put remaining coal and runite ore to the forge window.
4) I press "SMELT" but it dont open any transaction. Button is not active.

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed

**Comment by SivDraconis** [comment]
@Polypup - just retested and this is not working for me. I can only do a single forge and now I'm not able to forge at all, even after refresh.

Towards the end of today's video

**Comment by Polypup** [comment]
I don't know that it's been deployed yet

**Comment by Polypup** [comment]
I'm able to smelt multiple items in a row. What I did notice is that the inventory takes a few seconds to update after you successfully smelt. I'll have to check tomorrow night when my internet gets fixed. 

It's possible that the fix wasn't pushed to the deployed version. I will stay on top of this and get back to you 👍

**Comment by Polypup** [comment]
I believe I found the issue. On the backend we were calculating the correct lowestQuantity resource to apply to the resource count but on the frontend we were burning the total stacks of both resources which then would error out if you tried to use the stack it was saying was available. Fixed with the following the frontend. 

```
let quantities = forgeQuantities.value.map((quantity) => quantity);
  const lowestQuantity = Math.min(...quantities);
  quantities = quantities.map(
    (quantity) => quantity - (quantity - lowestQuantity)
  );
  
```
