### ISSUE TITLE
[Bug]: Claiming equipment from stash and denying transaction bugs UI

### ISSUE THREAD

**Issue by Lazerthelazy** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Lazer_the_lazy#0343

### What happened?

I denied a transaction to claim equipment from stash. After i tried to claim items again no transaction pops up on MM.

### What browsers are you seeing the problem on?

Firefox

### Relevant log output / error message

```shell
stash clicked Game.vue:856:6
Player Tokens: 
Object { success: true, playerTokens: {…} }
StashInventory.vue:343:6
stash clicked Game.vue:856:6
Player Tokens: 
Object { success: true, playerTokens: {…} }
StashInventory.vue:343:6
Proxy { <target>: (2) […], <handler>: {…} }
StashInventory.vue:423:6
Object { success: true, signature: "0xcba098a4dd4a99f967b9c23e2de0e5fca6cc9b51cc37e037c613738be8ad75bf1d730dca2a99c6a6ef9b770b7bc8d5791bde721ea1c69dd5a2d91627ee3792811c", nonce: "rYsgB1YOqTCS" }
StashInventory.vue:449:6
MetaMask - RPC Error: Internal JSON-RPC error. 
Object { code: -32603, message: "Internal JSON-RPC error.", data: {…} }
inpage.js:1:54366
undefined helpers.js:13:4
TypeError: a is undefined
    ru helpers.js:13
    t StashInventory.vue:576
    s runtime.js:63
    r runtime.js:294
    k runtime.js:119
    Babel 2
runtime-core.esm-bundler.js:226:16
refreshing
```

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
This is an expected issue from a previous resolved issue of duplicating items. Once you generate a signature, we will not generate a new signature for you with out completing the last claim exactly. The frontend will soon help you in this regard completing your previous claim.

**Comment by Lazerthelazy** [comment]
Roger
