### ISSUE TITLE
[Bug]: Bonds issues

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

1. When buying a bond, the token remaining token does not update after your transaction is completed.
2. You can input negative numbers or number that are too high in the quantity field. When clicking on buy bonds when there is an invalid number, nothing happens. (No prompt or error message)
3. No transaction cancelled prompt like the other places.

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed
