### ISSUE TITLE
[Bug]: Hotkey does not work if chat is opened

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

If I have the chat box opened, but not selected, I will not be able to use hotkeys in a fight.

![image](https://user-images.githubusercontent.com/8630518/206938972-93bab6a4-adee-477e-9c9a-0f73b291affc.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
It's intentional cause the focus is on chat. The keyboard shortcut conflicts with being what is typed on. Example, if you ever want to type some number in the chat, it will never work. 

One solution is to have hotkey used with another key. Example: ctrl+1 and so on.. But not a big issue at present
