### ISSUE TITLE
[Bug]: Share feature - Blueprint image is shown as full item

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When using the in-game share feature, the image created when attempting to share a blueprint is the completed item.

![image](https://user-images.githubusercontent.com/8630518/206939526-e4cdade2-a92c-4932-96e6-d5b69ad6cc17.png)
![image](https://user-images.githubusercontent.com/8630518/206939568-49f95935-25ac-4518-840b-ca4a8db913d0.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed
