### ISSUE TITLE
[Bug]: Stash - Unable to claim certain items (No metamask prompt)

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When attempting to claim some items from the stash, some items prompt a metamask transactions, while other load indefinitely making them unable to be claimed.

Video : https://youtu.be/P0rA_apIvSw

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Related to #104. Once a claim in started on a specific item the user has to go through with the transaction. The frontend of this upgrade is in progress.
