### ISSUE TITLE
[Bug]: Mines - Spam click on 'keep searching' breaks UI

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

After gathering some resources in the mines, if you spam click fast enough the keep searching button, the UI breaks.
![image](https://user-images.githubusercontent.com/8630518/207041188-83556c05-fc16-4bd9-8014-f74e5d2392c5.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed.
