### ISSUE TITLE
[Bug]: An error message is displayed and the item cannot be claimed from "YOUR STASH".

### ISSUE THREAD

**Issue by mumuri1** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

mumuri#1890

### What happened?

On the loot screen displayed after a battle with a monster
1:Press the "CLAIM EQUIPMENT" button.
2:Select rejection on Metamask gas billing screen

I repeated the above operation and a bug occurred.
It is not known if it is reproducible.

Closing the browser and logging back in does not resolve the bug, and when I try to claim an item from "YOUR STASH", the error message "DIRECT_CLAIM_DISALLOWED" appears at the top of the screen and I am unable to claim the item.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output / error message

```shell
DIRECT_CLAIM_DISALLOWED
```

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by mumuri1** [comment]
For some reason, I was able to claim only the "healing potion (15% HP recovery)" under "YOUR STASH".

When I try to claim other items (equipment, healing potions, materials, etc.), the error message "DIRECT_CLAIM_DISALLOWED" appears at the top of the screen and I cannot claim them.

**Comment by mumuri1** [comment]
After successfully claiming the "healing potion (15% HP recovery)" under "YOUR STASH", other recovery potions can now be claimed.

When I try to claim items other than recovery potions (equipment, materials, etc.), the error message "DIRECT_CLAIM_DISALLOWED" appears at the top of the screen and I cannot claim them.

**Comment by mumuri1** [comment]
We have encountered a bug that seems to be cascading with the above bug, and we report it here.

Both "The Wild Boar Inn" and "The Healer's Hut" are unavailable with the message "CALCULATING PRICE..." and are not available.

In "Grome's Bank", the choices are dark and nothing can be selected.

Marketplace" works fine.

**Comment by Polypup** [comment]
This is related to #104 and is expected to keep people from duplicating items. The frontend will be fixed soon to let users complete transactions easier.
