### ISSUE TITLE
[Bug]: DIRECT_CLAIM_DISALLOWED

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

![image](https://user-images.githubusercontent.com/8630518/207238433-89004dae-bc67-428f-b6f9-26e2ccb910bd.png)

I cannot claim items for my stash. This is the error message. No transaction pops up

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Brainiac1830** [comment]
> hey! this is a work in progress. To avoid this, try to claim the exact set of items you were previously claiming before rejecting the last transaction.

It has been a while since I have been not been able to claim items. I do not remember which item/set of items it was...

**Comment by Polypup** [comment]
You can claim again. It's been reset. This will be fixed soon but it's a work in progress currently. Related to #104

**Comment by SivDraconis** [comment]
This is broken for me too. I can't claim anymore @Polypup 
![image](https://user-images.githubusercontent.com/111258598/208329208-0a612c37-4ad3-4169-97c7-37d758ef92d7.png)

**Comment by Polypup** [comment]
It's still a work in progress. What were you trying to claim?

**Comment by SivDraconis** [comment]
https://youtu.be/n9t49711sNc?t=3028 - check it out

**Comment by Polypup** [comment]
Thanks, this is perfect. I just added stash event for equipment and consumables. Please let me know if it happens again 👍
