### ISSUE TITLE
[Bug]: End of fight character switching bug

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

You can bug out the character UI if after a fight finishes (monster dies). All you need to do is switch hero whenever it becomes allowed. You now have the health bar and action bar of the hero that killed the monster. It will refresh when entering a new fight / making a new action, but if you have no actions left, it will let you click on the action and then UI breaks.

VIdeo : https://youtu.be/LltQtqhO_Hc

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
I tried reproducing this multiple times but couldn't do it. :( May be it only happens during level up? In the video the hero levelled up? Will try again.

**Comment by Polypup** [comment]
I may have fixed it with another patch regarding handling stats on a fight win.
