### ISSUE TITLE
[Bug]: Blueprints in the marketplace are shown as completed items

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

Blueprints in the marketplace are shown as completed items instead of the normal blueprint icon.

Also they are listed with resources, is it intended?

![image](https://user-images.githubusercontent.com/8630518/207263504-37af3ee0-5c39-4d41-98bf-76f2dc8535dc.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
@sam-thewise Is this intentional or should they show the blueprint image?

**Comment by sam-thewise** [comment]
Hey these should be showing the blueprint image @Polypup

**Comment by neothon** [comment]
fixed
