### ISSUE TITLE
[Bug]: Number of items claimed in notifications wrong after the 2nd claim

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

There is a problem with the information the server gets back when claiming items the second time. I claimed 10 items first transaction and 5 items on the second one, but it showed 10 & 2.

![image](https://user-images.githubusercontent.com/8630518/207304426-55ef7271-e39f-4f0f-b4b5-019910ea46ce.png)

tx :1 https://testnet.snowtrace.io/tx/0x3d6bae75f7c60f190a6519a13142662390944682e0a5f266ab427e05b3f9aa34
tx2 : https://testnet.snowtrace.io/tx/0x48789d71f2db022b82fee0c439a9f57c5d6eb6a28f610f63c54abb8ccdb94217

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Brainiac1830** [comment]
I think it happens when you switch tabs while the transaction in processing.

**Comment by Polypup** [comment]
Okay, I'll try. I see the screenshots and txs just having a hard time reproducing. I'll keep trying 👍

**Comment by Chaney08** [comment]
Cannot replicate this issue, it shows appropriately every time. Think we should close for now.
