### ISSUE TITLE
[Bug]: Closing the "YOUR STASH" screen does not cancel the selection of the item.

### ISSUE THREAD

**Issue by mumuri1** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

mumuri#1890

### What happened?

1: Display "YOUR STASH" screen
2: Select item 1
3: Close "YOUR STASH" screen
4: Display "YOUR STASH" screen
5：Item 1 is not released from the selected state.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output / error message

```shell
None
```

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed
