### ISSUE TITLE
[Bug]: The "Attack" value in the item information listed in the pop-up window will change.

### ISSUE THREAD

**Issue by mumuri1** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

mumuri#1890

### What happened?

When hovering the mouse cursor over a weapon item's icon in the inventory, the "Attack" value in the item information pop-up window that appears changes.

The above bug occurs when the pop-up window of an item in the inventory is displayed repeatedly.

Once I re-logged in, the bug no longer occurs.
It is not known if this is reproducible or not.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output / error message

```shell
none
```

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
not reproducible. Tested multiple times.
