### ISSUE TITLE
[Bug]: Battle music continues to play after winning and going to claim stash

### ISSUE THREAD

**Issue by SlayerVan** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Van Gogh

### What happened?

Not a big deal, but battle music continues after beating foe and clicking claim stash. thought it might switch back to the general music. 

### What browsers are you seeing the problem on?

Firefox

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed
