### ISSUE TITLE
[Bug]: Unable to click share icon on item from loot screen after beating foe

### ISSUE THREAD

**Issue by SlayerVan** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Van Gogh

### What happened?

After winning battle, the loot screen comes up. After hovering over item, the item card comes up. If the share button is in the same area as the bottom item bar, the share button is not able to be clicked. The cursor changes but you can click it. Think its only for loot that is over the bottom item bar, because the other one higher works fine. 

### What browsers are you seeing the problem on?

Firefox

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
