### ISSUE TITLE
[Bug]: Sharing shows wrong item

### ISSUE THREAD

**Issue by SlayerVan** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Van Gogh

### What happened?

Went to share a Legendary Healing Potion, but the Enchanted Woodcutters Hatchet came up instead. 

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed
