### ISSUE TITLE
[Bug]: The forge is not working.

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When trying to craft my resources in the forge, it keeps saying "No result for this combination". Tried various of the know crafting recipes. Refreshed the page and still doesn't work. Tried to used different heroes and doesn't work.

![image](https://user-images.githubusercontent.com/8630518/207764353-d311f976-c507-4f39-a298-033e3dd71ec1.png)
![image](https://user-images.githubusercontent.com/8630518/207764469-adf7c49b-e7cc-404b-a4ba-e412b55cfe41.png)
![image](https://user-images.githubusercontent.com/8630518/207764499-81a4042a-87cf-48b7-bcd5-5eea28177145.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
<img width="399" alt="Screenshot 2022-12-14 at 10 24 36 PM" src="https://user-images.githubusercontent.com/85349906/207765291-d384a21d-5a08-4c40-931f-6c07f2159a37.png">


<img width="404" alt="Screenshot 2022-12-14 at 10 25 51 PM" src="https://user-images.githubusercontent.com/85349906/207765408-a6d6bdc0-cf9c-4fb3-98d7-fb525d0ee0ff.png">


It's working fine for me live right now.

**Comment by Polypup** [comment]
being out of turns now shows results and a disables the smelt button.
