### ISSUE TITLE
[Bug]: Forge issues

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When attempting to smelt something, the expected outcome shows an empty tooltip.
![image](https://user-images.githubusercontent.com/8630518/207776215-2c162be1-a92a-45a4-9758-f3ef9c8cb396.png)

When you smelt some ores, you will see a success message in the crafting box. This message is overflowing the box if the next item you attempt to craft requires a higher skill level than you currently have.
![image](https://user-images.githubusercontent.com/8630518/207776602-38ad335a-95ed-479f-b508-ad38363f20a5.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
Hey - at the moment, there is no further info for the bars, we will check if it is any different for in inventory as  these should be the same across the two

**Comment by Polypup** [comment]
fixed
