### ISSUE TITLE
[Bug]: Mining - Switching heroes when gathering action has started

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When mining, you can start the gathering action with an hero, then switch and get exp on the new hero (no action spent).

Hero 1 before : 
![image](https://user-images.githubusercontent.com/8630518/207777368-1e54a9b8-f035-4869-a8e9-e7c9912c4193.png)
Hero 1 starts mining (+26xp): 
![image](https://user-images.githubusercontent.com/8630518/207777488-3f437cfe-4431-49a3-b5f4-d6b7299bfb4f.png)
Hero 2 swaps in : 
![image](https://user-images.githubusercontent.com/8630518/207777576-99a3c129-e855-4ca4-9127-7c021d4c9085.png)
![image](https://user-images.githubusercontent.com/8630518/207778096-50c44f47-990b-47c4-9330-1b14ecf44179.png)

As we can see, hero 1 got 26 exp only, the rest went to hero 2

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by SivDraconis** [comment]
Confirmed that this is still possible. I can switch to a character without a pickaxe.

**Comment by Polypup** [comment]
@SivDraconis Can you confirm that in the mines, you can switch to character without pickaxe

**Comment by Polypup** [comment]
@Brainiac1830 The exp division is working as intended. The character receives exp based on their gathering skill. Starting the gathering will cost a turn but only for the character that started the mining/deepwood.

**Comment by SivDraconis** [comment]
@Polypup - I know what happened. I switched to a character with a pickaxe in their right hand, so the text shows the left hand weapon. You're correct that it's greyed out if the character doesn't have a pickaxe equiped.

![image](https://user-images.githubusercontent.com/111258598/209586231-8338a49e-2fef-4292-9706-c0d7c6028d1f.png)
