### ISSUE TITLE
[Bug]: Mining - You can mine resources above your gathering skill

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

You can gather items above your gathering skill by switching characters after finding a resource with your skilled gatherer.

![image](https://user-images.githubusercontent.com/8630518/207779465-0da05346-2f06-4a03-98d8-15597a66909a.png)
![image](https://user-images.githubusercontent.com/8630518/207779294-09a0f751-bb7f-422d-858e-e25754b8fdd2.png)
![image](https://user-images.githubusercontent.com/8630518/207779522-dc3b7e2b-79ca-4a9b-8325-a79e3ce3feb2.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
