### ISSUE TITLE
[Bug]: Mining stones

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

The display for gathering stuff is inverted before and after gathering. 

Before : "You find a **glowing gem infused rocks** of Gemstone of Precision!"
After : "Gathering Gemstone of precision **glowing gem infused rocks**"

Fix : Remove the last part of put it like it was shown before the action.

![image](https://user-images.githubusercontent.com/8630518/207782685-a8cae462-9ecb-4c77-8ebb-a0cfa81daea0.png)
![image](https://user-images.githubusercontent.com/8630518/207782962-cbde94e1-18e5-40d5-85f9-97da9bea2ff0.png)

Also, the text for these would need some improvement.
"You find a glowing pile of Gemstone of Precision" instead of "You find a glowing gem infused rocks of Gemstone of Precision!"
Would remove the word "stone" to make "You find a glowing pile of Enchanted Stone of Venom"
![image](https://user-images.githubusercontent.com/8630518/207783354-9fef0582-4ef0-47aa-9644-182fa9e693ef.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
Fixed in these PRs:
https://github.com/Dragon-Crypto-Gaming/hero-api/pull/74
https://github.com/Dragon-Crypto-Gaming/aurum-draconis-prototype/pull/199

Waiting on review/deploy
