### ISSUE TITLE
[Bug]: Death screen is empty.

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When your hero dies, there's a big black box in the middle with nothing in it.

![image](https://user-images.githubusercontent.com/8630518/207791063-d11f31cf-b995-4324-9969-34ac2e62075c.png)

This could be a good place to let people know they can swap heroes to continue the fight. (If they have healthy heroes)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Brainiac1830** [comment]
If you swap away from your dead hero, you shouldn't be able to go back to it in-combat. It allows a free "Flee from battle" without having to roll the dice to see if the flee succeeded. In new fight, if you have a dead hero, you can flee without risk anytime.

**Comment by Brainiac1830** [comment]
Also, I would make healer's hut the normal only location with a normal color when dead. It would make it more obvious that it is the only thing available for a dead hero.

**Comment by neothon** [comment]
fixed
