### ISSUE TITLE
[Bug]: Equipping items on dead heroes makes inventory / equipment disappear

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

If you try to equip a dead hero with a new piece of equipment, your whole inventory and hero equipment disappears.

You can get back hero equipment by switching heroes.

![image](https://user-images.githubusercontent.com/8630518/207793488-d58da0e4-9e7b-48f0-b6e1-4a2555046d50.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
