### ISSUE TITLE
[Bug]: Damage did not persist between battles

### ISSUE THREAD

**Issue by SivDraconis** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

Fought a battle and took damage. After the battle, Searched the Plains again and my HP was back to full (1300).

Video: https://youtu.be/a8k0Vsvl3KI?t=3643 - watch the HP right as the next battle starts.

### What browsers are you seeing the problem on?

Firefox

### Relevant log output / error message

```shell
Uncaught TypeError: i.value.pause is not a function
    e Game.vue:768
Game.vue:768:36
    e Game.vue:768
```

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Looking through the video, this is what happens:

1. User fights, loses health.
2. User goes to inn to heal. 
3. Completes transactions
4. User heals 
5. User immediately enters fight again.
6. Event Handler triggers the heal from 30 seconds prior during the new fight.

**Comment by SivDraconis** [comment]
So I heal from resting at the Inn, go through one battle and take damage, enter the second battle and the heal is triggered again? Interesting.

**Comment by Polypup** [comment]
We have a special tracker in the background for instances where a user buys something (heal) and then closes their browser so they'll still get credit for it. It works in the background. 

This is a bug but I identified what was causing it. We just need to lower the time for it. It was 30 seconds which is way too long.

**Comment by SivDraconis** [comment]
Almost certainly what happened in issue #3 , which is why you couldn't replicate it.

**Comment by Polypup** [comment]
Yes, most likely. 👍

**Comment by SivDraconis** [comment]
I can consistently replicate this using your steps above. Nice to have a free heal ;)

**Comment by Polypup** [comment]
Temporary fix with reduced time on event tracker.
