### ISSUE TITLE
[Bug]: Damage calculated before battle screen and animation appears

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

When entering battle, the damage for the first strike is calculated instantly, but the player only sees why later.
[Damage Calculation.webm](https://user-images.githubusercontent.com/120995580/208330206-9834a347-3528-47c0-b781-58a211efa500.webm)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Removed slight delay on frontend to match damage. Added slight delay for notification.
