### ISSUE TITLE
[Bug]: Claiming Items from stash

### ISSUE THREAD

**Issue by andika04kd** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#143]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Contact Details

Kaneshiro#7902

### What happened?

I claimed my items from the stash as usual but suddenly one time it show I've already pending claiming but the fact is I don't, and I can't do reject also

### What browsers are you seeing the problem on?

Chrome

### Relevant log output / error message

```shell
Direct_Claim_Dissalowed
```

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
What does it say that you still have to claim? Consumables, equipment, resources ect....

Rewards, consumables, and equipment are all WIP still.

**Comment by Polypup** [comment]
This has been resolved by adding stash event for consumables and equipment
