### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by adza404** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

sultan22#4062

### What happened?

the $DCAU and $DCAR faucet buttons cannot be clicked

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
There is a timer on these buttons. You can only claim once every 24 hours
