### ISSUE TITLE
Healing Hut [Bug]: Stuck at Calculating price from time to time

### ISSUE THREAD

**Issue by Jeeka7dcg** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Jeeka7#8723

### What happened?

A bug happened!

Going to the Healer's Hut from time to time - it gets stuck at 'Calculating Price' with only a refresh or two bringing it bcak with a DCAU quote for healing.

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by SivDraconis** [comment]
I haven't seen this one in a while. Perhaps it was fixed with other Healer Hut updates?

**Comment by Polypup** [comment]
This is most likely an issue of session expiring due to another bug. I'm marking this as fixed for now.
