### ISSUE TITLE
[Bug]: Grom's Bank UI elements overflowing

### ISSUE THREAD

**Issue by connorbode** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#147]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Contact Details

coconaut#2900

### What happened?

![image](https://user-images.githubusercontent.com/1156049/208473050-197c3608-cb33-4a94-8465-feec662c7909.png)

UI Elements are overflowing the Grom's Bank window (see image above)

OS: Ubuntu 
Browser: Brave 

Window dimensions:

![image](https://user-images.githubusercontent.com/1156049/208473351-e7144608-331a-4df1-9209-e42580d08b91.png)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
Fixed. It won't deform on smaller screens. Made completely mobile responsive.  

![image](https://user-images.githubusercontent.com/89765091/209738410-28d1db51-9ea5-46c4-bdec-124d1a8a1423.png)
