### ISSUE TITLE
[Bug]: Unable to claim DCAR or DCAU

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

Review #45 This is the same issue but #45 was unresolved

After logging first thing i tried was to claim DCAU or DCAR, attached video of fault

https://user-images.githubusercontent.com/120995580/208501686-f3eabd85-3dbd-4480-97a6-280099602577.mp4

[stage.aurumdraconis.dragoncrypto.io-1671477158565.log](https://github.com/Dragon-Crypto-Gaming/DCG-Bug-Reporter/files/10262046/stage.aurumdraconis.dragoncrypto.io-1671477158565.log)
[stage.aurumdraconis.dragoncrypto.io-1671477149722.log](https://github.com/Dragon-Crypto-Gaming/DCG-Bug-Reporter/files/10262048/stage.aurumdraconis.dragoncrypto.io-1671477149722.log)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Invalid session. Need to require users to login again instead of empty error.

**Comment by Polypup** [comment]
Fixed.
