### ISSUE TITLE
[Bug]: Combat bag UI - can select flee or weapon when bag is option showing potions

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

was in alpha, thought it was reported, so not sure if left intentional.

while combat bag is open, rear UI is not visible but can be selected
Needs a blank overlay to prevent accidental actions, video attached

[screen-recorder-tue-dec-20-2022-10-32-24.webm](https://user-images.githubusercontent.com/120995580/208528620-d894923f-8462-4292-9e24-fefa939ceb3a.webm)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Brainiac1830** [comment]
One of the bugs that were forgotten from discord! 
https://discordapp.com/channels/887555671963340862/1033155215932805120/1033155218034151456

**Comment by neothon** [comment]
fixed
