### ISSUE TITLE
[Bug]: while claiming DCA*, can still interact with Map breaks UI

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#152]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

1. Started Claim DCAU/R
2. before  completion of transactions I'm able to search plains
3. while waiting for the transaction to complete, started combat, 
4. On completion of the transaction and closing stash, kicked from combat and UI breaks
5. hard refresh but weapons are missing until swapping characters around.

see the video split into 3 files 
first is before the transaction completed
second is what happens when it completes and closed
third is what happens after

https://user-images.githubusercontent.com/120995580/208537655-f5579a09-7cec-41ef-bb43-609fef9d8d4e.mp4
https://user-images.githubusercontent.com/120995580/208537661-ac1409ba-6956-4ec7-bbae-651f96ce60d6.mp4
https://user-images.githubusercontent.com/120995580/208537668-2d72def3-9996-4f10-ac8d-6223a901828f.mp4

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by MistaLeigh** [comment]
this also applies to claim weapons and equipment

**Comment by Polypup** [comment]
Fixed
