### ISSUE TITLE
[Bug]: changing characters while healing - breaks UI

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

1. started the healing transaction
2. swapped characters
3. healing transaction completes 
4. Ui Breaks and the Character tile goes missing
5. hard refresh to reload

[While healing change char.webm](https://user-images.githubusercontent.com/120995580/208539501-cd2445f9-3c73-44be-b9fe-9de88c61c0bd.webm)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
