### ISSUE TITLE
[Bug]: going to deepwood without tool use bandages but uses fist wrong text? 

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#154]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

1. select hero without tools
2. go to deepwood
3. find and harvest resource
4. Button to "use bandage" shown
5. action is to "use fist" 

sorry for potato quality, but there is a 10MB limit..

[deepwood without a tool.webm](https://user-images.githubusercontent.com/120995580/208540536-c82092ba-27ee-4d37-aa0d-a2722b46aae4.webm)

![image](https://user-images.githubusercontent.com/120995580/208540718-835b4fc0-b5e7-4f03-aff9-0551c3ea161b.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed
