### ISSUE TITLE
[Bug]: Smelting - leaving the forge appears to have caused an issue

### ISSUE THREAD

**Issue by SivDraconis** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

1. I tried to forge 1056 Iron ore to Iron bars
2. Hit Smelt (I had 10 turns)
3. Approved Tx
4. Left Forge, Tx confirmed but did not receive XP or Iron Bars
5. Open Forge again and I see Iron Ore still in inventory
6. Try to Smelt again, nothing happens
7. Refresh doesn't help
8. Clicking Smelting button does nothing

![image](https://user-images.githubusercontent.com/111258598/208551967-c35f45c3-4874-4c4d-ad10-f938b9bb17e3.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
I believe we unmount everything when you leave the forge. Maybe we disable the button there until the tx finishes. I'll have to look through the code in the morning.

**Comment by Polypup** [comment]
Fixed for forging and crafters guild
