### ISSUE TITLE
[Bug]: After equipping from inventory and unequipping, item name in inventory will be same as unlocked item name

### ISSUE THREAD

**Issue by teamelon1234** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#156]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

tobatea

### What happened?

After equipping from inventory and unequipping, item name in inventory will be same as unlocked item name

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by teamelon1234** [comment]
![dragon](https://user-images.githubusercontent.com/121071556/208563630-c932a2c1-702d-46bb-b716-748d580dd5d3.png)

**Comment by sam-thewise** [comment]
Thanks for the report - I can't seem to replicate this one, what do you mean by unlocked item? :)

**Comment by teamelon1234** [comment]
I was using a translation tool, so it was a wrong translation. when the
equipment is removed. :D


2022年12月26日(月) 18:22 sam-thewise ***@***.***>:

**Comment by SivDraconis** [comment]
I tried this yesterday as well - couldn't replicate

**Comment by Polypup** [comment]
I'm not able to replicate. Closing the issue now.

**Comment by sam-thewise** [comment]
I think this issue is happening with google translate specifically

**Comment by teamelon1234** [comment]
I'll get back to you when I reproduce. It seems that there is always a
problem when I open it, but the procedure seems to be different

2022年12月29日(木) 5:04 sam-thewise ***@***.***>:
