### ISSUE TITLE
[Bug]: Message "You have a pending consumables claim" appear although items are claimed sucessfully and can not claim consumables anymore when claiming in "Your tash" and swicth to another tab

### ISSUE THREAD

**Issue by LhGiang** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

CSVanCo#2591

### What happened?

How to reproduce
1. Open Your Stash
2. Claim some items in Consumables tag
![image](https://user-images.githubusercontent.com/11839117/208609951-2a771c83-1bd1-489c-bf39-519fd36983a8.png)
4. Accept and wait for transaction in Meta mask
5. While claiming, switch to first tab and then try to select any item
6. Back to Consumables tag => Message "You have a pending consumables claim" appears although items are claimed successfully  
![image](https://user-images.githubusercontent.com/11839117/208609889-7bc5e602-56d8-4cfe-b49f-4baca7a68cc3.png)
7. Button "Reject pedning" is disable; click "Continue pending claim" => claimed items are still there 
8. Claim again => the above message shows again and we even can not close this dialog
![image](https://user-images.githubusercontent.com/11839117/208611170-d9d84301-d36a-4ff3-8dab-4d64ae8c5bf7.png)
10. Some cases that we can close but see message and can not claim any item anymore when opening dialog

### What browsers are you seeing the problem on?

Chrome, Firefox

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by cryptoshill** [comment]
Just to add to this, I am having the same issue, but when I try to complete the pending claim, I get the message "HASH_USED" and it returns to the original message.

![Screen Shot 2022-12-22 at 12 54 27 PM](https://user-images.githubusercontent.com/121113901/209197136-11fe096f-55d9-4c1f-8801-812a44d55138.png)

My issue also originated with the same bug mentioned in https://github.com/Dragon-Crypto-Gaming/DCG-Bug-Reporter/issues/188#issue-1507769641.

**Comment by Polypup** [comment]
We have everything ready for the reject pending claim which will resolve these types of issues. I think this has to do with an rpc issue on fuji when this occurs. 

In order for us to upgrade we need to wipe stats and I think we are going to wait on this. Ping me if you receive this again and I'll clear your signatures.
