### ISSUE TITLE
[Bug]: at the Inn, request a song is DCAR or DCAU - Button overlap

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

while at the Inn, i am unable to see if it will cost be DCAU or DCAR to request a song

![image](https://user-images.githubusercontent.com/120995580/208614359-6965b576-0168-464d-8cc2-458d56851313.png)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed
