### ISSUE TITLE
[Enhancement]: Free/Cheap way to reset to lvl 1

### ISSUE THREAD

**Issue by SivDraconis** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#160]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Siv

### What happened?

Wish List item - this may or may not be a good idea for the ecosystem so it'd need to be thought through

There should be a cheap way to reset your level back to 1. 

The first problem this solves is allowing people to experiment with one character - perhaps they realised that they shouldn't have dumped all their stats into crafting at lvl 1. Or they've decided they prefer a mage instead of a fighter. Or they find an amazing item they want to use but it doesn't fit their build.

The second problem it solves is when people buy an already leveled hero and it doesn't suit what they want to do with it. But knowing that they can reset it to zero when they purchase it allows them to buy the hero they want.

Would probably have to have some guardrails and heavy testing - if someone used it maliciously to reset another person's hero, that would suck. And perhaps a hero can only be reset once every 24hrs.

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
This was added with the amnesia potion :)
