### ISSUE TITLE
[Enhancement]: Make volume levels persist after refresh

### ISSUE THREAD

**Issue by SivDraconis** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#161]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Siv

### What happened?

A bit of a pet peeve, especially while streaming. Refreshing causes the volume to go back to 50% when the ideal on-stream volume is around 3% - is there a way to make it persist?

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
added
