### ISSUE TITLE
[Bug]: Loot dropped with no attributes

### ISSUE THREAD

**Issue by SivDraconis** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

Loot dropped with no attributes

<img width="472" alt="Screen Shot 2022-12-20 at 8 49 24 pm" src="https://user-images.githubusercontent.com/111258598/208649593-a1a401c4-9c94-4c74-93df-4320d2eceeb3.png">

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by SivDraconis** [comment]
It wasn't in Stash when I looked after clicking claim stash

**Comment by sam-thewise** [comment]
Resources don't have attributes - this is because your gathering skill was high enough to gather bones from a skeleton :)
