### ISSUE TITLE
[Bug]: Can not move map by cursor on Firefox browser  

### ISSUE THREAD

**Issue by LhGiang** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

CSVanCo#2591

### What happened?

I can not move map by cursor on Firefox browser => can not use functions in right side on map
Note: it works with Chrome browser, scroll mouse works as well
![image](https://user-images.githubusercontent.com/11839117/208656085-2dcfe376-cc0f-430a-8729-438493a1f7c1.png)

### What browsers are you seeing the problem on?

Firefox

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
Hi LhGiang, which operating system are you using for this?

**Comment by LhGiang** [comment]
Please see details info in below image
![image](https://user-images.githubusercontent.com/11839117/209540263-88a62798-1781-4ac7-81f8-db08ff288855.png)

**Comment by LhGiang** [comment]
Now it works well with my browser => I will close the ticket.
