### ISSUE TITLE
[Bug]: Some buttons (Your inventory,...) are disable for alive hero when switching from dead hero

### ISSUE THREAD

**Issue by LhGiang** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

CSVanCo#2591

### What happened?
1. Hero just got slain from battle => 4 buttons in right side (Your inventory,...) are disable
![image](https://user-images.githubusercontent.com/11839117/208666970-ce666462-4af6-4330-9878-f5672363e246.png)

2. These buttons are still disable for alive hero when switching from dead hero
![image](https://user-images.githubusercontent.com/11839117/208662030-b73b0486-5e0e-4e4d-8ba7-9ed59b5769c3.png)

Note: Reload browser => now these buttons are enable for both alive and dead hero

### What browsers are you seeing the problem on?

Chrome, Firefox

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed.
