### ISSUE TITLE
[Bug]: Dragging &dropping item from "Inventory" to "Character Equiqment" dialog for dead hero makes all items disappeared

### ISSUE THREAD

**Issue by LhGiang** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

CSVanCo#2591

### What happened?

1. Open "Inventory" to "Character Equiqment" dialog simultaneously for dead hero
![image](https://user-images.githubusercontent.com/11839117/208665501-2063625f-1653-4e1f-9b78-8490599705ef.png)
2. Drag & drop an item from "Inventory" to "Character Equiqment" 
=> all items disappear
![image](https://user-images.githubusercontent.com/11839117/208665659-b4180659-98a4-4a60-b3bf-bbaf6e8252f7.png)

Note: The above buttons are only enable when we reload browser after hero dies

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed: https://github.com/Dragon-Crypto-Gaming/aurum-draconis-prototype/commit/d331a6e264192da5a262c8daf9cad411eee784c3
