### ISSUE TITLE
[Bug]:  character disappears

### ISSUE THREAD

**Issue by djtrinh412** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

DJHU#2593

### What happened?

When i click too fast at Deepwood, this is happening both current character and UI game disappear
I must F5 browser to get them normaly
![1](https://user-images.githubusercontent.com/101915615/208697449-ead08ebe-67a8-491f-8cd4-d3e30b04d746.png)
![2](https://user-images.githubusercontent.com/101915615/208697457-520cc3f1-bcf4-4edd-8618-656088e81041.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
I'm having trouble replicating this. How are you clicking so fast?

**Comment by SivDraconis** [comment]
I can replicate this on my Mac/FF
<img width="1512" alt="Screen Shot 2022-12-22 at 12 10 12 pm" src="https://user-images.githubusercontent.com/111258598/209039801-4be91628-e525-4f77-893d-eb9a7dced5ad.png">

**Comment by Polypup** [comment]
Are you using the keyboard to do this? If so, what buttons? 

If you're clicking which part are you clicking so fast. Sorry, not sure why I can't replicate

**Comment by SivDraconis** [comment]
Here's the video from yesterday. I'm clicking on search again using a touchpad on a Mac/FF.

https://youtu.be/vbUyC-Clhf8?t=160

**Comment by Polypup** [comment]
My fingers are having trouble clicking that fast but in your video you can see the `Keep Searching` appear again for a split second before loading the next data. I think this was being clicked causing a session issue. I added a slight delay to that becoming active agains which should solve the issue. Hopefully.
