### ISSUE TITLE
[Bug]: Cant cancel trancstion

### ISSUE THREAD

**Issue by djtrinh412** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

DJHU#2593

### What happened?

When claim some items from stash, if u choose reject comfirm transaction then you won't be able to choose another item to claim
until you agree to trade for the items you initially selected

![3](https://user-images.githubusercontent.com/101915615/208700072-7b8c4db2-1992-46f2-9a73-f3ef94ea864b.png)
![4](https://user-images.githubusercontent.com/101915615/208700086-1ab7d6b5-dcd4-4353-aa21-df2b7f0c4172.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
You'll be able to reject soon. It's currently not available until a new wipe occurs.
