### ISSUE TITLE
Claiming rewards from daily quest and forging do not give XP

### ISSUE THREAD

**Issue by SivDraconis** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

Claiming rewards does not give XP.

Forging also does not give XP.

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
I receive the following error when claiming daily rewards

```
index.js?4360:2258 Uncaught (in promise) ReferenceError: result is not defined
    at eval (index.js?4360:2258:1)
    ```

**Comment by Polypup** [comment]
Fixed the error with claiming daily quests. Checking forge now

**Comment by Polypup** [comment]
Fixed the issue with forging not give exp. https://github.com/Dragon-Crypto-Gaming/hero-api/commit/9312db2a12e425f5171e7fd34c18f9714890db1b
