### ISSUE TITLE
Forge item added to inventory without forging

### ISSUE THREAD

**Issue by cryptoshill** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#170]
When at the forge, if you put an item into one of the slots, it shows you what you will forge from that item.

![Screen Shot 2022-12-20 at 10 23 19 AM](https://user-images.githubusercontent.com/121113901/208713301-1178a3a6-21bd-4db0-a077-b3fa6b841c32.png)

The game allows you to drag the unforged item into one of the slots meant for items to be put into the forge.

![Screen Shot 2022-12-20 at 10 23 29 AM](https://user-images.githubusercontent.com/121113901/208713480-640e0712-f4fd-484a-918c-d61bbd0a3ef5.png)

If you then click the "Remove" button, that unforged item goes into your inventory, along with the material that you would have used to forge it (notice both iron ore and iron bars in the inventory). 

![Screen Shot 2022-12-20 at 10 23 40 AM](https://user-images.githubusercontent.com/121113901/208713645-3eee6f44-4b8a-409e-a228-5ec2de12e966.png)

The item remains in your inventory even after leaving the forge.

![Screen Shot 2022-12-20 at 10 23 50 AM](https://user-images.githubusercontent.com/121113901/208713903-4d4bf096-a4c9-4a59-be2d-687fae407482.png)

Note that I cannot use the iron bars (to craft, etc.). The game also does not let me use the forge anymore.

![Screen Shot 2022-12-20 at 11 15 42 AM](https://user-images.githubusercontent.com/121113901/208714209-0966e6c4-6982-442e-ae7b-f61fd223a0f0.png)

I have to leave the game and re-enter in order to clear the iron bars from my inventory and resume the game as normal.

**Comment by Polypup** [comment]
<img width="655" alt="Screenshot 2022-12-20 at 3 47 26 PM" src="https://user-images.githubusercontent.com/85349906/208763384-388e4974-30c9-4f7d-bd94-1be55b4be647.png">

**Comment by Polypup** [comment]
Fixed and merged
