### ISSUE TITLE
[Bug]: Unsuccessful resurrection

### ISSUE THREAD

**Issue by WesToStakuj** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

friendly.fire#8915

### What happened?

![Screenshot 2022-12-20 103049](https://user-images.githubusercontent.com/119375694/208729871-64f334bd-575c-4755-a70a-662cd186c62e.png)
![Screenshot 2022-12-20 103145](https://user-images.githubusercontent.com/119375694/208729875-72f5a1e5-ab9d-467b-9b8f-fabd5ce6c9e9.png)
I am dead so I went to healers hut as usually in this case to do resurrection but this time twice my transaction was confirmed but the health didn't came back
https://testnet.snowtrace.io/tx/0x60ecf1e3f22287bd213717df8b7e0c68f5b913837c773289b62a8125194f4079
https://testnet.snowtrace.io/tx/0x60a63f80ccf6f4b20d6abed0960e7b1dcadd1eb8cf7331312f4f6a022b148c8d

I needed to relog from the game and log again to get my health back but I lost in DCAU and AVAX because of doubled transaction. 

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
The backend was crashed for a 30 minute period while multiple people were playing. Someone was taking it done consistently trying to replicate a bug. This is probably what caused this error. I have tested the resurrection multiple times and cannot replicate this.
