### ISSUE TITLE
[Bug]: during combat, any/all party can be swapped inc 1 in combat that breaks game

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

1. started combat
2. changed party to be different people - bug 1? would a party be locked during combat?
3. changed person in combat, after this you can hear map sound - combat exited assume
4. return from the character selection screen to find the combat screen still going
5. continue fighting but then the screen locks and have to hard refresh
6. after hard refresh starts to combat again but weapon on swapped characters is missing
7. change from and back to character to make it return

![image](https://user-images.githubusercontent.com/120995580/208739735-c8113729-8853-4ba5-8857-8e0693244354.png)
[Character change bug.webm](https://user-images.githubusercontent.com/120995580/208739744-04a098d4-e5ae-4da3-8d83-8d0c6c25eb4e.webm)

[Character change bug.webm](https://user-images.githubusercontent.com/120995580/208743483-8365329b-2ddf-4f99-a8ea-52c59ededc10.webm)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed: https://github.com/Dragon-Crypto-Gaming/aurum-draconis-prototype/commit/dbdac3ed78ad4edaade5751682b315306dcdf7e4
