### ISSUE TITLE
[Bug]: Chest "of health" doesn't add health

### ISSUE THREAD

**Issue by SivDraconis** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#176]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Siv

### What happened?

![image](https://user-images.githubusercontent.com/111258598/208849322-8b203f9e-66a3-4a61-9493-0a7b16bea19e.png)

+6 magic but no health/endurance

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
@sam-thewise can you clarify if this item is supposed to add health

**Comment by sam-thewise** [comment]
Yes definitely - I'll make the changes for this one

**Comment by sam-thewise** [comment]
We're reviewing this code now, then it'll be on the test server

**Comment by sam-thewise** [comment]
Fixed and merged - will only be for newly generated health items since the changes
