### ISSUE TITLE
[Bug]: Marketplace - Need to keep approving equipment

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When listing an item on the marketplace. You have the option to approve this item or approve all. When clicking on approve all, you still need to approve your next items that you want to sell.

![image](https://user-images.githubusercontent.com/8630518/208865495-1cd3ccc6-2579-4641-91a6-966f67c619f8.png)

![image](https://user-images.githubusercontent.com/8630518/208865416-344bc0db-1ead-4d78-9cc6-9c5a26c1500f.png)

It is the same with approve DCAU. Once I've done it once, I still need to do it again when reopening the marketplace / change filters.

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
I tested for quite some time and cannot replicate. I believe it may be an issue with Fuji rpc being overloaded. I"m going to close for now but will reopen if I can replicate.
