### ISSUE TITLE
[Bug]: Quick mining bug in the mines/deepwood 

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When gathering in the mines / deepwood, you can press 'space' to gather more quickly the nodes once you have already tapped it once. See this : https://youtu.be/lYx1Qq1qblE?t=1014

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by SivDraconis** [comment]
Is this a bug? I think that's normal.

**Comment by benpatterson1** [comment]
I came to report this but found this bug, but if its normal, it feels janky.

**Comment by Polypup** [comment]
fixed the mines. Working on a separate issue related to deepwood
