### ISSUE TITLE
Marketplace - rarity sort is not working

### ISSUE THREAD

**Issue by SivDraconis** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

Confirming still not fixed - transferred from Discord

Sort by rarity ascending and descending and it's not in the right order

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed.
