### ISSUE TITLE
[Bug]: The forge - Crafted items do not disappear

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When crafting in the forge, if you attempt to craft an item, send the transaction, then remove the items from the crafting slots, you will not see the items disappear when the transaction goes through. They get burned on the blockchain, but they keep showing up in your inventory even after refresh. If you try to use these items, it does not work.

How to reproduce ; 
-put iron ore in the forge.
-smelt iron ore.
-accept transaction#
-click on remove before transaction goes through
-try to use the items after the transaction goes through

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Brainiac1830** [comment]
Edit : Resources are burned, turn is not lost, no items sent to stash & no experience gained.

**Comment by Polypup** [comment]
fixed
