### ISSUE TITLE
[Bug]: It is possiable open other functions if "Your Stash" dialog is opening => unexpected behaviors

### ISSUE THREAD

**Issue by LhGiang** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

CSVanCo#2591

### What happened?

1. Click "Your Stash" dialog and then open Wild Boar Inn, Crafter's Guild,... => "Your Stash" dialog cover screen so we can not click some buttons
![image](https://user-images.githubusercontent.com/11839117/208909007-2b2c8543-39b7-4b63-ab9d-4fe3817c66b3.png)
2. Try to close "Your Stash" dialog => close all

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
It's not really a bug. Both states close when set to wandering. Closing this issue for now.
