### ISSUE TITLE
[Bug]: pushing spacebar at the end of combat takes to straight into next combat

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

1. completed combat
2. before clicking examine loot push space bar (activating the next hidden screen?)
3. next combat round is started directly without seeing loot screen

https://user-images.githubusercontent.com/120995580/208989847-8ad26389-d20e-4894-9ac4-bc84a6cdf833.mp4

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed
