### ISSUE TITLE
Grom's Bank - Available DCAU and DCAR Balance

### ISSUE THREAD

**Issue by andy8810** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#183]
When you click on Grom's Bank, you cannot see your available balance of DCAU and DCAR like you can on the Inventory page. You have to close the window and open the Inventory window in order to figure out how much funds you have available.

_Originally posted by @andy8810 in https://github.com/Dragon-Crypto-Gaming/DCG-Bug-Reporter/issues/157#issuecomment-1359900366_

**Comment by Polypup** [comment]
<img width="412" alt="Screenshot 2022-12-22 at 11 38 00 PM" src="https://user-images.githubusercontent.com/85349906/209271861-dd0d37a4-fc7e-43ae-8227-fb490c3f84a8.png">

You should be able to see your balances on the top right corner of grom's bank
