### ISSUE TITLE
Enhancement- Marketplace - Hover Over Image 

### ISSUE THREAD

**Issue by andy8810** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#184]
Hi There,

I noticed today that when hovering over an item in the Marketplace, I cannot see how the stats improve or are less than my current armor or weapon. When reviewing loot from fighting in the plains I can see in blue font color the +/- each item does to my stats if I were to equip it; however, this does not seem to come up when I'm in the Marketplace reviewing an item to purchase.

**Comment by sam-thewise** [comment]
Fix in PR: https://github.com/Dragon-Crypto-Gaming/aurum-draconis-prototype/pull/196 
Waiting on review/deploy
