### ISSUE TITLE
[Enhancement]: No Real Notification When Quests Are Complete

### ISSUE THREAD

**Issue by andy8810** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

@andy8810

### What happened?

Hi There,

This comment goes along with a previous thread where I addressed leveling up. Similarly, when you complete a quest of killing "x" number of monsters in the Plains, you do not see anything on the screen that catches your eye that you've completed the quest. You just kind of notice that you completed it when you check in on them. It would be nice to see a "flash" or sound similarly to when you level up (as previously suggested) to notify you on the main screen that your character has completed a quest.

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed and merged
