### ISSUE TITLE
[Enhancement] When You Level Up, Your HP and Turns Should Reset

### ISSUE THREAD

**Issue by andy8810** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Leveling up is obviously a big accomplishment. When achieving another level, it would be awesome if your HP and number of turns reset to full, so you can keep playing. Often times, I am finding myself trying to squeeze in one or two more battles to not have to stop and heal up, knowing that I am going to level up. It's just a little disappointing that nothing like this happens and I end up spending the fee anyway to heal. Should be free in-game.

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by andy8810** [comment]
I see that when you adjust your stat points after leveling, that your HP goes to full. It would be nice if you also reset the Turns as well.

**Comment by Polypup** [comment]
@sam-thewise What do you think about this enhancement

**Comment by andy8810** [comment]
I like the HP reset when you level. To me, I think you should also get more turns. The amount of gas fees being spent in all areas of the game do slow it down, so if you level, it would be nice if you were rewarded in more turns as well as the HP.

**Comment by sam-thewise** [comment]
yeah I think when we implement the new level screen we should do this as part of it, it makes sense
