### ISSUE TITLE
[Enhancement]: Stash Gets Overwhelming Over Time

### ISSUE THREAD

**Issue by andy8810** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

@andy8810

### What happened?

Hi There,

One more comment for the night, after testing this beta version out again. I have now achieved Level 7! (Woot! Woot!) 
I am starting to notice that my stash is starting to fill up with items that are either too low in stats now, or are not solid drops and would not sell in the Marketplace. I say this because I have to pay a gas fee in order to list something on the marketplace, so if it's not valuable to even me in my quest, I can't imagine someone else is going to want to buy a pair of gloves with no stat points.

Something to think about here, is maybe either having the capability to hide unwanted items? Or just discard them. I remember from my Diablo days, that after a long day's battle, you could "Discard" items in your stash or there was a person in town available that would buy back your items at more of a "face value." This was a really cool feature I enjoyed in Diablo, as it solved two problems: 1) I cleared out my stash at the end of my time playing. 2) I earned a little bit of extra cash for the fights I did accomplish, even though the items' values were not huge, it was nice to see that spending the time to pick up that axe that had a few extra stat points had some sense of value to me for holding onto. 

I am not sure how to even begin with valuing the armors/weapons here in this game; however, I thought this would be a good example to bring up, with the hope of solving the main problem, which is if I do get something I like and want to use on my character, I now have to open up my stash, scroll all the way down to the bottom, and try to find it amongst all the other things I picked up along the way while fighting.

Hope this helps. Sorry, this is a longer explanation that some of the other minor bug fixes I previously wanted to bring to your attention. Hope this one gets read as well. I appreciate you and the team for reading through these as I truly hope this game is a major success.

Best Regards,

Andrew 

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
We're releasing the bulk breakdown function soon to help with this

**Comment by neothon** [comment]
Also, at present the drop rate is too high for testnet. On mainnet, the drop rate is going to be way lower :)

**Comment by sam-thewise** [comment]
Bulk breakdown is released now
