### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LhGiang** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

CSVanCo#2591

### What happened?

Sometimes I got Session Expired when opening "Your Stash" dialog although I just login in
It often happens if there was Session Expired before
![image](https://user-images.githubusercontent.com/11839117/209132074-7ac68412-1455-4567-af3d-dffd60b139cd.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Intended use
