### ISSUE TITLE
[Bug]: combat screen frozen

### ISSUE THREAD

**Issue by Gonad4** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

erencb#4341

### What happened?

I got combat screen frozen problem at least 1 time at 10 turn. I have to relog and lost a turn with all heroes. 
<img width="1280" alt="Ekran Resmi 2022-12-22 15 07 36" src="https://user-images.githubusercontent.com/121234389/209132235-50547d0a-e79c-40e3-b23c-21362c3535b6.png">

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Gonad4** [comment]
<img width="1280" alt="Ekran Resmi 2022-12-22 15 55 49" src="https://user-images.githubusercontent.com/121234389/209138986-5ee13d05-f67e-485b-9126-d59db84180a7.png">

**Comment by Polypup** [comment]
Server has been crashing, we put in a fix just now to fail gracefully while we figure out a certain bug.
