### ISSUE TITLE
[Bug]: Lost character

### ISSUE THREAD

**Issue by djtrinh412** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

DJHU#2593

### What happened?

Today when i login in game, #1649 char is lost. When i check my wallet then only 2 chars are minted. i dont know why
![4](https://user-images.githubusercontent.com/101915615/209137263-c4705828-32f7-48ea-9f6d-8fd3b65e7681.png)
![6](https://user-images.githubusercontent.com/101915615/209136886-222141e5-a39e-47b7-8e75-f75665fcf731.png)
![4](https://user-images.githubusercontent.com/101915615/209136784-0fe0354a-09c2-4371-8b62-785d189b8e40.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Jeeka7dcg** [comment]
I had the same issue - a character I levelled up to 5 was gone

**Comment by Polypup** [comment]
We recently did a mass mint of tokens for testnet users. You didn't own the nft for the character 1649 previously and it was minted to someone else during this period. 

Sorry for the issue.
