### ISSUE TITLE
Suggestion: When Hovering Over HP Bar - Add % of Health Left

### ISSUE THREAD

**Issue by andy8810** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

@andy8810

### What happened?

It would be a nice feature to add the percentage of health you have left in a window by the mouse cursor when you hover over the HP bar. That way, you can see how much actual % of health you have left. Then you will quickly be able to tell which healing potion you should use from your inventory. Would certainly help at higher levels when you have much higher endurance levels.

As always, thanks for hearing my suggestions!

Long time gamer, first time crypto-gamer. Thank you so much for letting me test your project out.

Best Regards,

Andrew

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
Fixed on PR https://github.com/Dragon-Crypto-Gaming/aurum-draconis-prototype/pull/197
Waiting on merge/review
