### ISSUE TITLE
Suggestion: Cannot see % of Health Potion in Bottom, Center Bar

### ISSUE THREAD

**Issue by andy8810** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I may have mentioned this already, but it is kind of annoying that I have to go to the inventory page to remember how much each health potion percentage is. It would be nice it you were to hove your mouse over the potion on the bottom central bar, that the window opened up showing what percentage of HP the potion is.

Thanks! 

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
merged
