### ISSUE TITLE
[Bug]: It is possible to click button "Use Resurrection Elixir" a lot of times

### ISSUE THREAD

**Issue by LhGiang** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

CSVanCo#2591

### What happened?

It is possible to click button "Use Resurrection Elixir" a lot of times (for other heal button are disable after clicked)
=> many requests are sent

![image](https://user-images.githubusercontent.com/11839117/209196441-13281924-de57-45eb-8d62-97c7bfa41091.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed
