### ISSUE TITLE
[Bug]: quest log bugs out - no visible quests / wont open

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

1. open the quest log to review quests
2. switch between characters to review
3. 1 or more characters' quest logs become bugged, unable to view or open

[stage.aurumdraconis.dragoncrypto.io-1671741842565.log](https://github.com/Dragon-Crypto-Gaming/DCG-Bug-Reporter/files/10290261/stage.aurumdraconis.dragoncrypto.io-1671741842565.log)

Video to be attached...
[review quests1.webm](https://user-images.githubusercontent.com/120995580/209224046-badbe676-8217-4307-b523-dd9db8270d45.webm)
[review quests2.webm](https://user-images.githubusercontent.com/120995580/209224752-ec6c947b-e1f9-4e09-9942-6523cf554589.webm)
[review quests3.webm](https://user-images.githubusercontent.com/120995580/209224771-4e3c5095-7ca0-4d83-8ac6-302f11244286.webm)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
