### ISSUE TITLE
[Bug]: Burn request from meta mask when using 1 in combat

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

1. Started combat using click request
2. used 1 instead and then get matamask notification for burning?

[MM Burn window.webm](https://user-images.githubusercontent.com/120995580/209226020-464d30c9-c692-4165-9350-7160d449524e.webm)
[stage.aurumdraconis.dragoncrypto.io-1671743231537.log](https://github.com/Dragon-Crypto-Gaming/DCG-Bug-Reporter/files/10290367/stage.aurumdraconis.dragoncrypto.io-1671743231537.log)
![image](https://user-images.githubusercontent.com/120995580/209226098-df63d593-4650-4b2f-b20f-fcf98471840f.png)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
In the hotbar, pushing 1 will use a consumable. I'm not sure how to repeat this.

**Comment by MistaLeigh** [comment]
hey, i think i found how it was triggered, i noticed it was ok most the time.
It firsts happens after switching characters, then pushing 1 immeddialty,
there is a moment before the weapon is equiped, this triggers the burn notice

**Comment by Polypup** [comment]
I can see the consumable move to the slot 1 when I switch characters so I am disabling the hotbar for 100ms while switching characters.

**Comment by Polypup** [comment]
Fixed
