### ISSUE TITLE
[Bug]: Mulit reward for quests of same creatures for x1 character- Bug?

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

not sure if bug or intended
1. When multiple quests of same creature are listed for character, kill its rewarded across them all
2. character with Lurker x3 quests kill x1 lurker got counter against x3 quests for lurkers
![image](https://user-images.githubusercontent.com/120995580/209227339-4060291c-fcd7-4b57-8109-54fdcec2a954.png)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
@sam-thewise Let us know if this is intended or a bug 👍 Thank  you🙏

**Comment by sam-thewise** [comment]
This is intended, if you happen to have multiple daily's, each kill still counts towards it
