### ISSUE TITLE
[Bug]: "replacing" ring on slot 2 with a new ring, replaces ring in slot 1 

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

1. have 2 rings equipped
2. replace ring 2 with another ring
3. ring 1 is replaced unexpectantly
video attached and log attached

[ring replacement.webm](https://user-images.githubusercontent.com/120995580/209242667-de61a047-a13e-4c1f-a3bf-9cee50e181f7.webm)

[stage.aurumdraconis.dragoncrypto.io-1671752024370.log](https://github.com/Dragon-Crypto-Gaming/DCG-Bug-Reporter/files/10290921/stage.aurumdraconis.dragoncrypto.io-1671752024370.log)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed
