### ISSUE TITLE
[Bug]: Wrong healed number using 100% heal iteam in battle

### ISSUE THREAD

**Issue by LhGiang** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

CSVanCo#2591

### What happened?

Wrong number displays in hero icon (it even is 0)
![image](https://user-images.githubusercontent.com/11839117/209260703-2639b760-b1d0-43b5-9b78-5ce3293ad546.png)
![image](https://user-images.githubusercontent.com/11839117/209260746-6a7e3fe9-9ca9-43fe-bf98-ffabe3bb3d83.png)

Correct number is shown afterwards
![image](https://user-images.githubusercontent.com/11839117/209260853-6968b180-a71a-4db1-872f-a0c1c1c52447.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
