### ISSUE TITLE
Crafting issues / UI

### ISSUE THREAD

**Issue by SivDraconis** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#20]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Siv

### What happened?

While trying to craft, moving various resources and removing them caused UI issues

Clip: https://clips.twitch.tv/SmellyAnimatedPineappleKappa-aTU1thPtq7gVQZj0

Full video (watch near the end): https://www.twitch.tv/videos/1647661916

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Exact error:

```
inputResourceIds [ 20041 ]
Error: Unable to extract accountName with provided information.
at Object.createTintedImage (/app/data/ImageProcessor.js:12:43
at Object.convertBlueprintToItemData (/app/GameCategories/Crafting.js:161:42
at Object.craftFromBlueprint (/app/GameCategories/Crafting.js:102:40
at /app/app.js:4277:47
```

**Comment by Polypup** [comment]
<img width="98" alt="Screenshot 2022-11-09 at 6 35 36 PM" src="https://user-images.githubusercontent.com/85349906/200965060-6c2d6ac3-3704-4b64-a3ef-b4177048cf5d.png">
<img width="76" alt="Screenshot 2022-11-09 at 6 36 01 PM" src="https://user-images.githubusercontent.com/85349906/200965062-5e8dcd3b-0beb-440f-9c7a-d749d447bd23.png">

Everything is now working as intended with the updated connection string. Will push to staging shortly
