### ISSUE TITLE
[Bug]: On level up, HUD disappears (no icons)

### ISSUE THREAD

**Issue by benpatterson1** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#201]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Contact Details

BenGK🔰#4861

### What happened?

Level'd up and the HUD disapeared, See screenshot for console logs and (lack of) HUD as it shows up.
Left the 2nd hero image though

![image](https://user-images.githubusercontent.com/2111036/209263727-0ab3fc92-3b5b-43d6-972d-485e89f6247d.png)

related to: https://github.com/Dragon-Crypto-Gaming/DCG-Bug-Reporter/issues/150

### What browsers are you seeing the problem on?

Chrome.

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Server has been crashing, we put in a fix just now to fail gracefully while we figure out a certain bug.
