### ISSUE TITLE
[Bug]: declining forge NFT approve leaves UI to Hang and have to Hard refresh

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

1. open forge
2. put ore in
3. click approve NFT
4. decline Meta Mask 
5. Screen hangs - should recieve a decline message and allow to be close?
6. hard refresh req

[declining NFT approval for forge.webm](https://user-images.githubusercontent.com/120995580/209273953-80c758f1-004f-415e-98ac-70cf2db62e8f.webm)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
