### ISSUE TITLE
[Bug]: Dead with full HP

### ISSUE THREAD

**Issue by LhGiang** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

CSVanCo#2591

### What happened?

When waiting for healing by potion, join a battle and die with very low HP condition
![image](https://user-images.githubusercontent.com/11839117/209284672-ce9c79e6-9b7d-4634-a2b3-7c05aefc2c93.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
