### ISSUE TITLE
[Bug]: Free turns at mines

### ISSUE THREAD

**Issue by sam-thewise** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#204]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Contact Details

Akita066#5730

### What happened?

submitting on behalf of Akita

how to reproduce: 
rest in boar inn (rent a room)
go to mines immediately, spam mining action .
you will mine and get resources
prompt for mining action repeatedly.
everything is fine until now...
but your energy will reset back to 10  (after 5-15 seconds)  even if you do play for (mine) 4-5 turns beforehand.

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
@neothon will be working on this issue which involves updating our EventTracker mechanism for blockchain transactions.

**Comment by Polypup** [comment]
Fixed here: https://github.com/Dragon-Crypto-Gaming/hero-api/pull/50
