### ISSUE TITLE
Suggestion: When pulling up a potion in battle - Need Health %

### ISSUE THREAD

**Issue by andy8810** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

So when you're in the middle of a battle and you need to use a potion, it does not come up on the display of what % of HP will be regained. Would be super helpful to see this as when I'm in the middle of fighting, I sometimes forget which potion is better than the other to use.

Thanks!

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
definitely needs to show on the icon or somewhere obvious, thanks Andy!

**Comment by neothon** [comment]
Added secondary description to combat consumable buttons.
