### ISSUE TITLE
Enhancement: More Experience Gained for Large Fights

### ISSUE THREAD

**Issue by andy8810** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#206]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What happened?

It would be nice if you gained more experience and received better loots when you win a battle with an opponent that is much better than you. My current HP is 6,500. I took down a monster at 17,000 HP. I had to use several potions and fought my way through it. Unfortunately I only received the same amount of experience points as I would for fighting something of lessor quality. I also did not receive any good drops in loot. This has happened on multiple occasions. It would be nice if this were cleaned up.

Thanks as always for hearing my opinion.

Best Regards,

Andrew

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
Thanks Andy, it does boost luck but yes should definitely be noticeable, was thinking something similar when I was playing too
