### ISSUE TITLE
[Bug]: Grom's bank bond error when inputing text instead of number.

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When input a 'string' instead of an integer in the text field to buy bonds, an error is displayed, but the error is not detailed like the other messages.

![image](https://user-images.githubusercontent.com/8630518/209422557-3b3440b4-a059-45f8-b2c0-b9752e70e82e.png)
![image](https://user-images.githubusercontent.com/8630518/209422583-062dda91-8998-4b58-9b82-9edca55c3566.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
