### ISSUE TITLE
[Bug]: Quests - Youtube crypto trader - completed out of bound

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When you have the quest Youtube Crypto Trader, it goes out of bounds when you complete it. Taking 2 rows.

Quest enhancement : Please leave the quest log opened after you click claim reward and the loot appears.
Please have a filter for completed quests. It's getting really crowded after a few days of accepting quests.

![image](https://user-images.githubusercontent.com/8630518/209423390-d6d2d694-ce79-4b39-bbb6-38fa161d35c5.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
<img width="748" alt="Screenshot 2022-12-24 at 9 19 39 AM" src="https://user-images.githubusercontent.com/85349906/209439779-a2227427-592b-4294-8f63-439b987d5a05.png">

Easier to identify quests. Enhancements are coming after all bugs are resolved 👍

**Comment by Polypup** [comment]
Fixed
