### ISSUE TITLE
[Bug]: Quests - Cannot open quest logs on other characters

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When completing a quest on one character, you cannot open the quest log anymore on other characters. Fixes upon refresh.

1. Completed a quest and claim reward
2. Switch character
3. Try to open quest log

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed
