### ISSUE TITLE
[Bug]: Link to tweet Resurrection Potion as Loot is broken

### ISSUE THREAD

**Issue by s1lv3rback** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#210]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

kyrpto

### What happened?

Nothing happens when you click the link to tweet Res potion as loot

![Screenshot 2022-12-24 065358](https://user-images.githubusercontent.com/121063058/209434950-24b57522-ed6f-4e2f-983c-6579e18a86b9.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
