### ISSUE TITLE
Suggestion: Bond Rewards are Weak

### ISSUE THREAD

**Issue by andy8810** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#211]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

I have 4 Bonds currently in place. Left it alone overnight, roughly 8 hours. Earned 17 DCAR, which seems low?
I earn way more than in one fight. I know this is more of a passive income opportunity, but just something to think about.

Thanks,

Andrew

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
The bond rewards do not have any thought behind the amount being dispersed at the moment. This is a customizable option and were just started to people can get a feel for them.
