### ISSUE TITLE
[Bug]: Can't gather in the mines with pure gathering level 1

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

If the gathering skill of my hero is 1 (without including bonuses), I can't gather in the mines anymore. This is due to the fix where you could swap characters and mine stronger resources when swapping characters. Now the 'gathering' check is done after ;search the mines' so it means that level 1 gathering cannot gather iron with level 5 gathering required.

![image](https://user-images.githubusercontent.com/8630518/209589729-ee327039-67c5-4d48-8ad0-a3117d089669.png)
![image](https://user-images.githubusercontent.com/8630518/209589757-90439871-25ca-4cbf-bbc3-f031239e194b.png)

Fix : reduce iron ore gathering required to level 1
Enhancement : Make everyone be able to visit the mine, but show the required items / gathering required before being able to mine.
Enhancement : show item tooltip when hovering over the resources in the mines. That way we can see the gathering required.

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Brainiac1830** [comment]
#99

**Comment by sam-thewise** [comment]
We're reviewing this code now, then it'll be on the test server

**Comment by sam-thewise** [comment]
This is fixed and merged
