### ISSUE TITLE
[Bug]: Crafting - Stones of power do not get burned when crafting

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When crafting items with enchanted stones of power, the stones of power do not get burned and return to inventory upon refresh. 

https://testnet.snowtrace.io/tx/0xdba917d5ba3c2bf5ac7ed46b40e8031672c33f5d456b2e93cb348b08e370c3eb
![image](https://user-images.githubusercontent.com/8630518/209644373-d2f61b51-2bc0-41f3-abcd-87e52021c8eb.png)
![image](https://user-images.githubusercontent.com/8630518/209644466-a4698e97-e51a-4649-946d-61d967aff3ea.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed and merged
