### ISSUE TITLE
[Bug]: *Server crashing bug*  Crafting - Attempting to put better quality resources does not change the outcome of the item

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

1- Attempting to craft a short spear
2- Put required materials (wood and iron)
3 - Everything works fine, output is shown on the screen.
**4- Put higher quality resources instead of wood and iron. (Styxium bar and ancient yew wood)**
5- Output doesn't change
6- Attempt to refresh
7- server is ded

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
Fixed now with some code changes
