### ISSUE TITLE
[Bug]: Unable to mine Gem Shards

### ISSUE THREAD

**Issue by s1lv3rback** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

kyrpto

### What happened?

Each time I find Gem Shards in the mine, I am unable to mine them bc the Start Mining button is greyed out. Tested multiple times and unable to mine each time. I am able to mine other materials that I find. 

![image](https://user-images.githubusercontent.com/121063058/209689225-e8aee55a-9265-46e9-aa38-0d1e8d9c4c4d.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Your gathering skill isn't high enough. We can add a notification at the top 👍

**Comment by sam-thewise** [comment]
This one should be fixed with my PR https://github.com/Dragon-Crypto-Gaming/aurum-draconis-prototype/pull/171 https://github.com/Dragon-Crypto-Gaming/hero-api/pull/54

**Comment by sam-thewise** [comment]
Fixed and merged
