### ISSUE TITLE
[Bug]: Searching mines does not cost a turn

### ISSUE THREAD

**Issue by s1lv3rback** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

kyrpto

### What happened?

Searching in mines does not cost a turn. Only costs a turn when you actually mine the material. Can keep searching until you find the material you prefer. 

![image](https://user-images.githubusercontent.com/121063058/209689715-3e07b8ac-0417-4ca5-9cb4-ce19e3672c8c.png)

![image](https://user-images.githubusercontent.com/121063058/209689763-3cca8589-466c-4807-8f96-45e7c4b41d5a.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
@sam-thewise Is this intended or should we start charging a user a turn per search?

**Comment by Polypup** [comment]
Fixed
