### ISSUE TITLE
[Bug]: Breakdown from inventory doesnt work

### ISSUE THREAD

**Issue by Lazerthelazy** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Lazer_the_lazy#0343

### What happened?

Inventory -> item -> crafting menu -> break down button doesnt do anything

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
Duplicate of https://github.com/Dragon-Crypto-Gaming/DCG-Bug-Reporter/issues/230
