### ISSUE TITLE
[Bug]: multiple selected items stay selected when equipped, inventory closed, character changed - linked breakdown

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

1. have multiple selected items for breakdown
2. equipped x1 of the selected items
3. swap characters and close inventory
4. all items stay selected
5. activate breakdown and they are destroyed even if equipped
- should they be unselected when equipped?
- should all items be unselected with inventory is closed?
- if x1 selected item was equipped, there's no easy way to find out which one it is unless all items are unequipped
- when going to the crafting hall they stay selected also from previous screens
- refreshing the session clears any selections / equipped selections.
- after selling to market its still selected - message, you are not owner appears

![image](https://user-images.githubusercontent.com/120995580/210015193-3335764d-e888-4fe5-906d-54b719c5c41c.png)
![image](https://user-images.githubusercontent.com/120995580/210015209-4995a195-bd4f-4546-a385-709dbd69d8c1.png)
![image](https://user-images.githubusercontent.com/120995580/210015230-28174fc1-671a-47a6-ac2a-7c8baad62c5d.png)
![image](https://user-images.githubusercontent.com/120995580/210015253-d65865f7-0c98-4230-9358-6ecd8ec4ae68.png)
![image](https://user-images.githubusercontent.com/120995580/210015280-9af70587-b596-414b-85f6-6009ffa0c6dd.png)
![image](https://user-images.githubusercontent.com/120995580/210015296-b7c3e477-42b3-4be5-8cc1-70296624a1a3.png)
![image](https://user-images.githubusercontent.com/120995580/210015708-dc8340ab-1ab4-4be6-a9c8-ca9b01d8b1a9.png)
![image](https://user-images.githubusercontent.com/120995580/210019043-b71e7039-d354-4bab-aa85-cbddf1d23b07.png)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed
