### ISSUE TITLE
[Bug]: breakdown failed and message appeared - erc721 - owner query for nonexistent token

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

1. this selected item wooden shield by itself or as part of other items
2. click breakdown
3. nothing happened and a message appeared
![image](https://user-images.githubusercontent.com/120995580/210016521-5fef1c7a-a822-4758-a854-47f8d48ce23a.png)
![image](https://user-images.githubusercontent.com/120995580/210016400-e424d857-4213-4c39-8591-eb264b722982.png)

[stage.aurumdraconis.dragoncrypto.io-1672352128179.log](https://github.com/Dragon-Crypto-Gaming/DCG-Bug-Reporter/files/10322315/stage.aurumdraconis.dragoncrypto.io-1672352128179.log)
[stage.aurumdraconis.dragoncrypto.io-1672352121510.log](https://github.com/Dragon-Crypto-Gaming/DCG-Bug-Reporter/files/10322316/stage.aurumdraconis.dragoncrypto.io-1672352121510.log)
[stage.aurumdraconis.dragoncrypto.io-1672352139023.log](https://github.com/Dragon-Crypto-Gaming/DCG-Bug-Reporter/files/10322317/stage.aurumdraconis.dragoncrypto.io-1672352139023.log)
[stage.aurumdraconis.dragoncrypto.io-1672352134175.log](https://github.com/Dragon-Crypto-Gaming/DCG-Bug-Reporter/files/10322318/stage.aurumdraconis.dragoncrypto.io-1672352134175.log)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by MistaLeigh** [comment]
note i was clicking breakdown from main window not from the crafting menu, 
228 shows a bug related to crafting menu which is happening on all items

**Comment by Polypup** [comment]
@MistaLeigh What is your heroId. I need to investigate.

**Comment by MistaLeigh** [comment]
1026 was the one gifted to me for beta

**Comment by Polypup** [comment]
1400, 6422, 6424, 6242, 7605, 8743, 8752, 8764, 8768, 8772, 8796, 11889, 11977, 12032, 18098 had similar issues on the equipment. This needs monitoring to find equipment that are not minted but have { isStashed: false} in db. 

Disabling stash check on hero-api for now.

**Comment by Polypup** [comment]
merged
