### ISSUE TITLE
[Bug]: Find event in planes - swapping characters and leaving it breaks UI

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

1. find event started in planes
2. swapped character
3. unable to activate find event
4. leave it to exit or search plans break UI
5. search plans again but are unable to proceed - the message you are already in an encounter
6. unable to enter a current encounter - have to refresh to get encounter to show up
7. if I heal the UI breaks again - the character disappears from the map screen and the character select the screen
8. other map events like Inn etc now bugged out also.
9. carry out refresh and log in but the same issues happen
10. you have to find and switch to the original hero who activated the encounter to fix

![image](https://user-images.githubusercontent.com/120995580/210027454-0771d509-9e83-43a3-ba48-6bc010e73493.png)
![image](https://user-images.githubusercontent.com/120995580/210027456-656bc3e1-8e62-4da8-b425-ae3151c9413f.png)
![image](https://user-images.githubusercontent.com/120995580/210027530-6189fc7b-ca98-4eca-b445-20caa71a86dd.png)
![image](https://user-images.githubusercontent.com/120995580/210027537-bcab72f1-7769-41a3-b7df-901dfd7625c0.png)
![image](https://user-images.githubusercontent.com/120995580/210027703-64ab39bb-9fd1-41da-a8d8-b3edb945a411.png)
![image](https://user-images.githubusercontent.com/120995580/210027758-eeebeec2-d020-401b-9e62-23445f620a88.png)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed and merged

**Comment by MistaLeigh** [comment]
@Polypup after changing character i can still leave or serch plains to recreate the bug, would need to block option 2 and 3 also
![image](https://user-images.githubusercontent.com/120995580/210037387-a32f1f33-4ef3-4920-86b4-3ec16b62b04b.png)

**Comment by Polypup** [comment]
All should be resolved now
