### ISSUE TITLE
[Bug]: free healing from heath equipment

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

1. char with heath equipment reaches heath below what is added in equipment
+300 +250 +350
3. remove equipment 
4. (803 - 300 = 503) - 250 = 253,  all ok so far
5. removed final piece - 350 = 253, 
- heath stays the same
- expected character to die or drop to 0 or -100 etc
7. added back on the items removed and gained more heath than i started with
8. a character with only 100 / 1 endurance and loaded with health equipment would be able to constantly free-heal within 100 units from maximum
 
started at = 803/2000
removed all = 253 / 1100
added back on = 1263 / 2000

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
merged

**Comment by MistaLeigh** [comment]
@Polypup i found a workaround, i can use equip or move equipment to replace it to remove items still and then gain free health, would need to block this also.

**Comment by Polypup** [comment]
This should be fixed now too 👍
