### ISSUE TITLE
[Bug]: Blueprints select for breakdown allows transaction but nothing happens afterwards

### ISSUE THREAD

**Issue by MistaLeigh** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Mista Leigh#2981

### What happened?

1. select blueprint in the inventory
2. select breakdown
3. approve the transaction
4. result nothing is broken down and the blueprint is retained in the inventory
5. try again and now i get the message that I am not the owner 
- cannot list on market afterward -related to owner?
- note while breakdown is initiated, you and also queue the same item to be sold or vise vursa resulting in errors.
- each button should be blocked from each other while transation is in progress
- 
![image](https://user-images.githubusercontent.com/120995580/210032598-2ccaf828-4d25-4309-a6c1-99e163521eae.png)
![image](https://user-images.githubusercontent.com/120995580/210032860-b70ae917-51a6-48fc-8d67-d84442136830.png)
![image](https://user-images.githubusercontent.com/120995580/210032644-fea9fc0d-dfa5-47a8-a784-986c31e9faed.png)
![image](https://user-images.githubusercontent.com/120995580/210032972-e418b903-0fcc-4fb1-9eed-73cc5a9eb090.png)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Blueprint is being burned but we're not updating in our backend.

**Comment by Polypup** [comment]
Related to limit size of breakdown and blueprint breakdown. Fixed and merged.
