### ISSUE TITLE
[Bug]: Crafting certain resources causes server crash and does not recover

### ISSUE THREAD

**Issue by Polypup** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

PolyPup

### What happened?

<img width="937" alt="Screenshot 2022-12-29 at 11 10 05 PM" src="https://user-images.githubusercontent.com/85349906/210033679-028803fc-b7e6-409d-ab2c-eafd70e2816a.png">

If it's going to fail, should do so gracefully. The previous issue was for smelting, this is for crafting.

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by MistaLeigh** [comment]
i believe i was crafting at the time..  i put a stone into the blueprint socket......
testing crafting i have found other issues, i will log in shortly, this i won't do again thou

**Comment by MistaLeigh** [comment]
@Polypup seems like it happened again, this was then due to using Bronzewood/other wood in the recipe the calls for normal wood and swapping the woods around etc. 
sorry, i thought it was from the stone issue but must be the wood.

**Comment by Polypup** [comment]
It's an npm package on our deployment

**Comment by MistaLeigh** [comment]
Would you like the bugs mentioned above as separate tickets?

**Comment by Polypup** [comment]
No, they are the same issue, but the cause is an npm package trying to generate an image. No need to create new issue.

**Comment by Polypup** [comment]
Related to #220

**Comment by sam-thewise** [comment]
Fixed now with some code changes
