### ISSUE TITLE
[Bug]: Stash breakdown - Some items do not disappear after breakdown

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

I wanted to test the new stash breakdown feature and encountered a bug where some of my items that were broken down still showed up in my stash. I tried to break them down again and my UI disappeared. 

![image](https://user-images.githubusercontent.com/8630518/210053514-33d0fe09-72e4-4a95-b161-d4f8d6bc10ce.png)
 About 160 items out of the 565 showed up again after the first breakdown.

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Related to limit size of breakdown and blueprint breakdown. Fixed and merged.
