### ISSUE TITLE
[Bug]: Elixir of life / Legendary healing potion

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

This potion has 2 names. When looting : ELixir of life 
![image](https://user-images.githubusercontent.com/8630518/210057465-0f403dbd-ad70-425b-95f3-c518fdb57915.png)

When in stash / inventory : Legendary healing potion 

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
Hey - this is just because the item is already in-game, once we reset the item DB it'll have the new name :)
