### ISSUE TITLE
[Bug]: Spam clicking in the mines bugs out UI

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

If you keep clicking on search again in the mine after collecting a node of resources, the UI will bug out.

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Brainiac1830** [comment]
![Uploading image.png…]()
Spam click on this!

**Comment by Polypup** [comment]
I'm not able to replicate this.

**Comment by Polypup** [comment]
Closing this since it can no longer be spammed
