### ISSUE TITLE
[Bug]: Level 1 gathering in the mines cannot hit the iron ore more than once.

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When gathering in the mines with a level 1 pure gathering skill (without the boosts included), you can only hit the iron ore node once. After that the button is greyout out. 

![Uploading image.png…]()

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Brainiac1830** [comment]
![image](https://user-images.githubusercontent.com/8630518/210059841-c74266fa-a3e5-4b84-aa79-0792d8b76667.png)
#215

**Comment by neothon** [comment]
fixed
