### ISSUE TITLE
[Bug]: Display wrong HP after apply Endurance points

### ISSUE THREAD

**Issue by LhGiang** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

CSVanCo#2591

### What happened?

Level up => Add and apply Endurance points => wrong HP display
![image](https://user-images.githubusercontent.com/11839117/210123387-65f4c3cb-30c9-4cac-ad36-31f294ac5a67.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
