### ISSUE TITLE
[Bug]: Flee'ing the scene after finding a chest or a man in the plains, gives a error message.

### ISSUE THREAD

**Issue by grizlydev** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After you try to flee the scene after finding a box in the plains, or the drunken man, you get a message saying "You are not in an encounter". It should either take you back to the home screen or be greyed out as you are now forced back into the plains (after also losing health to the trapped chest).

![image](https://user-images.githubusercontent.com/112823249/210173696-2067bd0a-bf4d-4ce2-9cde-b158341287d8.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Shark1989** [comment]
yeah had now the same situation :-)

**Comment by sam-thewise** [comment]
Fixed in this PR: https://github.com/Dragon-Crypto-Gaming/aurum-draconis-prototype/pull/198
waiting on review/deploy
