### ISSUE TITLE
[Bug]: Trying to breakdown in inventory (crafting menu -> breakdown) is not working.

### ISSUE THREAD

**Issue by grizlydev** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If you try to break down an individual item in your inventory, after going to the crafting menu, you can't break it down. It simply won't do anything. 

![image](https://user-images.githubusercontent.com/112823249/210174012-4333fcf8-c1cd-4639-9773-31e51e4aab49.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Chaney08** [comment]
This has been fixed and pushed.
