### ISSUE TITLE
Can't search the plains due to pending token claim.

### ISSUE THREAD

**Issue by attilafulop** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#245]
<img width="831" alt="image" src="https://user-images.githubusercontent.com/76530842/210174062-3bdc0db6-d863-4085-8ed1-1b4888062739.png">

For some reason, I can't search the plains as whenever I click on the button it gives me a "pending token claim" error.

**Comment by neothon** [comment]
somehow signature was generated even though token value was 0 

Fixed a bug where claim button gets disabled when token value is 0. 

![image](https://user-images.githubusercontent.com/89765091/210175254-45fc1d1a-d403-4da7-9673-5ac96c3df90c.png)

**Comment by neothon** [comment]
Need to ensure the quantity in signature is used and not the quantity in stash.

**Comment by neothon** [comment]
This one is closed. Will open a different issue for using the quantity in signature.
