### ISSUE TITLE
[Bug]: Trying to breakdown my old leggings gives me error: "Equipmentburn: Not owner of equipment"

### ISSUE THREAD

**Issue by grizlydev** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried to breakdown my old leggings and it gave me a message saying "Equipmentburn: Not owner of equipment" However I still have the item in my inventory. I can still swap it out with my newer leggings and it just works fine. I tried refreshing and hard refreshing but the item is still in my inventory. Hero id #40

![image](https://user-images.githubusercontent.com/112823249/210174244-b9ed659c-a742-4170-8bb0-f2a1db4a4892.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Related to #244
