### ISSUE TITLE
[Enhancement]: Help videos

### ISSUE THREAD

**Issue by neothon** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Use self hosted help videos instead of YT cause it shows related videos at the end.

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
https://github.com/Dragon-Crypto-Gaming/aurum-draconis-prototype/pull/188

**Comment by Polypup** [comment]
Fixed by @neothon
