### ISSUE TITLE
[Bug]: When you have no turns left, the approve DCAR button is greyed out in the crafters guild

### ISSUE THREAD

**Issue by sam-thewise** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#250]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

You should be able to approve, then know you have no turns instead of the approval being greyed out 

![image](https://user-images.githubusercontent.com/87108890/210191430-9cea3ee7-ebfb-4178-b8d9-cabc040bb222.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
