### ISSUE TITLE
[Bug]: Spamming autoplay button on plains kills enemy way faster

### ISSUE THREAD

**Issue by grizlydev** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If you spam the auto-play button endlessly the fights is over in a very quick time frame related to the normal fighting time. I don't really know if this fits into category bug, but it seems to be having a ''advantage'' over what the game usually should be doing.

On the first few ''attacks'' it seems normal, but if you keep spamming it to the max you will see that it suddenly starts hitting very quick or even skipping the animation after the 3/4th hit.

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed
