### ISSUE TITLE
[Enhancement] Allow craft quantity when crafting blueprints

### ISSUE THREAD

**Issue by sam-thewise** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#256]
Especially relevant when crafting potions - being able to select the quantity and having a "max" button for the number of resources you have

**Comment by Polypup** [comment]
Ping me when/if you need help with the blockchain aspect 👍

**Comment by Chaney08** [comment]
Just needs a little styling for now so closing as complete as all the functionality is there.
