### ISSUE TITLE
[Enhancement] Scaling EXP for crafting items

### ISSUE THREAD

**Issue by sam-thewise** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#257]
No exp is rewarded for crafting an item; much like the DCAR required, the EXP received should scale for crafting items.

**Comment by Polypup** [comment]
Do we have a min/max value here? We can match this exp value to the DCAR spent. Min DCAR spent on crafting is 10, max is currently around 135. Exp can be 1:1,2:1, or 3:1 on DCAR spent. 

Min: 30 exp
Max: 405 exp. 

Those would be our values with a 3:1 ratio on DCAR scaling.

**Comment by sam-thewise** [comment]
That looks about right - perhaps it should scale up a bit more on the high end though

**Comment by sam-thewise** [comment]
@Polypup  i've implement this one in this PR https://github.com/Dragon-Crypto-Gaming/hero-api/pull/73

**Comment by Polypup** [comment]
Merged, great work by Sam 👍
