### ISSUE TITLE
[Tweak]: Update DCAU rate being used in healer's hut.

### ISSUE THREAD

**Issue by neothon** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#259]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What happened?

Tweak the settings to use optimum DCAU in healer's hut. At present it's charging too high. Need to test out the ideal scenario that will be used on the mainnet.

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Current Pricing: 

$0.025 per HP of healing (25000000000000000 wei)
Healing 5000 HP costs just over 18 DCAU

Just killing your hero and resurrecting costs ~3.1 DCAU for this same hero at level 10

**Comment by sam-thewise** [comment]
A better option would be $0.00025 per hp.

What are the resurrection costs at the moment?

**Comment by Polypup** [comment]
Resurrection cost is $2.5 per level at the moment

**Comment by Polypup** [comment]
This has been updated.
