### ISSUE TITLE
[Bug]: Completed quest after fighting different mob

### ISSUE THREAD

**Issue by s1lv3rback** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

krypto

### What happened?

Got a message for completing a quest of killing 5 paperhands after defeating a Wild Tiny Dragon. Prior 2 mobs I fought were not paperhands either.
![image](https://user-images.githubusercontent.com/121063058/210356609-b29e05f8-d05f-4134-8f31-40a0e325be52.png)
 

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
I've tested this several times and everything seems to be working correctly. I checked your encounters and see that you have killed a total of 7 paperhands mob. I'm closing this for now but will keep an eye out.
