### ISSUE TITLE
[Bug]: When harvesting cotton in the Deepwood, I can continue to harvest indefinitely

### ISSUE THREAD

**Issue by SivDraconis** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

- Rested at inn
- Went to deepwood
- Searched twice
- (turns reset to 10 due to Inn bug)
- Started harvesting cotton
- Clicked at least 30 times, receiving 20-21 cotton and XP each time

Works without resting, so the Inn bug doesn't relevant. Only works with Cotton.

Video to follow

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
Fixed in https://github.com/Dragon-Crypto-Gaming/hero-api/pull/75
Waiting for review/merge

**Comment by Polypup** [comment]
fixed and merged
