### ISSUE TITLE
[Bug]: potion of elixir and resurrection at healer's hut

### ISSUE THREAD

**Issue by akita066** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#267]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Akita066#5730

### What happened?

1)use elixir of resurrection while dead

-healer's hut will be still accessible
-go to healer's hut before the potion resurrects you
-click on resurrection prompt,
2)wait until the pot resurrects you
you are alive and you have a pending transaction.
3)now approve the (healer's hut) transaction.
The game tries to resurrect you while you're already alive...

UI crashes (all interactable ui disappears, needs a hard refresh)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
merged
