### ISSUE TITLE
[Bug]: Healing mid-fight with pre-arranged metamask TX prompt.

### ISSUE THREAD

**Issue by akita066** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#269]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Akita066#5730

### What happened?

1) Click any type of potion on the item-bar that is above XP-Bar

after you click, a metamask prompt will pop up.
from now on the game doesn't allow you to go to the plains.
we can bypass this by checking the deep woods and coming back.

voila! you can now go to the plains, and can drink your ready-to-use potion whenever you want, without losing a turn during the fights.

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed
