### ISSUE TITLE
[Bug]: Autoplay doesn't keep going after using a ressurection elixir

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

1- Have autoplay on
2- Die
3- Use resurection elixir
4- Accept transaction and wait for server to acknowledge transaction
5- Autoplay doesn't continue after you're resurected, but the button is still turned on.

Fix proposal : Turn off autoplay on death / make autoplay work after resurection elixir is used

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
merged
