### ISSUE TITLE
[Bug]: Level up - You can heal twice from level up

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

1- Fight 
2- Level up (get healed)
3- Fight again until low hp
4- Put stats point (get healed)

Proposed fix : Remove hp from allocating stats points / remove healing on level up

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
We no longer give full health when updating stat points.
