### ISSUE TITLE
:Enhancement: Add a "Claim all" button for resources in the stash

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#273]
It would be nice to have a button to "Claim All" resources for the erc1155 items (potions & resources). It would speed up the gameplay if you're looking to withdraw all your resources / potions.

**Comment by neothon** [comment]
There were a few contract limitations on how many nfts we can mint in one go. That is the reason we are limiting to 10 items being minted in each category.

**Comment by Polypup** [comment]
There is a contract limitation here.
