### ISSUE TITLE
[Bug]: Amnesia Gas resets action bar

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

Not sure if it's a bug, but the Amnesia Gas resets the hero's turn back to 10. It makes this potion remove the need to go rest at the inn to get more turns.

1- Play until you run out of turns
2- Use amnesia potion
3- Spend points
4- Play until you run out of turns
5- Use amnesia potion
6- Spend points
7- Keep doing this

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
@sam-thewise I don't think this is intended, but please let me know.

**Comment by sam-thewise** [comment]
No - it shouldn't affect turns
