### ISSUE TITLE
[Bug]: Crafting - Disappearing blueprints

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

Blueprints disappear if you drag and drop a new blueprint over the current blueprint on the crafting bench. 

1- Go to crafter's guild
2- Drop blueprint # 1 on crafting bench
3- Drop blueprint  # 2 on top of blueprint # 1
4- Blueprint # 1 is gone until page refresh

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
Approved and merged
