### ISSUE TITLE
[Bug]: When gathering/mining, if you search with 1 turn, you can't gather in that turn #262

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

Bug #262 not fixed. 

![image](https://user-images.githubusercontent.com/8630518/210692266-c049c020-7b5c-4a75-9ec6-5e217bb5309c.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
approved/merged, thanks!
