### ISSUE TITLE
[Bug]: Resurection Elixir usable while alive in-combat

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

It is possible to use the resurrection elixir as a 100% healing potion if used in-combat. Need to use hotkey to use it because it doesn't show up in the bag.

1- Look up what hotkey is Ressurection Elixir
2- Search the plains
3- Press the Ressurection Elixir hotkey
4- Get fully healed.

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
approved and merged :)
