### ISSUE TITLE
[Bug]: Crafting - DCAR price for blueprint doesn't update until crafting materials are placed

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

1- Go to crafter's guild
2- Place an epic blueprint
3- DCAR price doesn't update
4- Place required materials to craft the item
5- DCAR price updates

![image](https://user-images.githubusercontent.com/8630518/210695907-e7d7a2a8-4c0f-4c1b-a944-36e401c41a37.png)
![image](https://user-images.githubusercontent.com/8630518/210695945-931bcfa9-f607-4305-90c9-c55f8179add7.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
Reviewed and merged :)
