### ISSUE TITLE
[Bug]: Spam clicking "keep searching" in the mines error

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

Here's a video of the bug happening. Recorded today

https://youtu.be/4_p9YvC9eNY

#239 @Polypup 

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
No matter what I do, I cannot reproduce this issue.
