### ISSUE TITLE
[Bug]: Mining / Gathering - "Start gathering" button showing wrong info

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When mining and gathering, the "start gathering" button shows that it takes a turn to take the action when it doesn't anymore. "Keep searching" should be the one to say (1 turn) ![image](https://user-images.githubusercontent.com/8630518/210701862-5f4c95a1-32c7-47fd-831b-a5ad276e9184.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
Reviewed and merged
