### ISSUE TITLE
[Bug]: Hero's health shows > 0 even though dead. But behaves like a dead hero.

### ISSUE THREAD

**Issue by neothon** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#286]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What happened?

<img width="619" alt="image" src="https://user-images.githubusercontent.com/89765091/210858035-f6d26fed-380c-4631-b5bc-b4261040febd.png">

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
That's due to servers restarting and providing health
