### ISSUE TITLE
[Bug]: Direct Claim Disallowed - Withdraw item, cancel transaction, then break the items down

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

0- Go in the stash
1- Select items to withdraw
2- Click withdraw
3- Reject the transaction
4- Select the same items in the breakdown section
5- Break down the items
6- Attempt to claim any items
7- Direct Claim Disallowed bug
8- Cannot reject claim or continue pending claim

![image](https://user-images.githubusercontent.com/8630518/210930848-a62bd3eb-9188-4f29-9973-89bc4103d7c8.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
This is being worked on in a very large overhaul to this section. It combines several existing issues.
