### ISSUE TITLE
[Bug]: not sure if this is a bug but happened ocasionally, getting matched with level 1 mobs.

### ISSUE THREAD

**Issue by akita066** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#296]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Akita066#5730

### What happened?

not sure if this is a bug, but i still want to raise some awareness. 

after resting in tavern i go to plains immediately, and more than few times i'm getting matched with 1 level mobs. 
my level is 12

also the loot i got from 2 level 1 mobs were 27.5 DCAR and 0.325 DCAU

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
This is intended functionality, you're suppose to meet lower level mobs occasionally.
