### ISSUE TITLE
[Bug]: Crafting does not work probably for me.

### ISSUE THREAD

**Issue by grizlydev** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried crafting a pair of boots and it confirmed on the blockchain. I have not received any items and i waited about 5 minutes before clicking the ''remove'' button to get my blueprint back. The blueprint returned to my inventory for 2 seconds and then it disappeared. I then refreshed my browser and the blueprint was back in my inventory. Tried crafting again and got the same issue, also with a confirmed blockchain tx.

![image](https://user-images.githubusercontent.com/112823249/211196037-e231a325-5d32-4629-bbcd-83d33edce4b1.png)

https://testnet.snowtrace.io/tx/0x37c1f42df9c5b175e109683d4a177f591e5e3f1c5978764a81e70f8e5bd582b2

https://testnet.snowtrace.io/tx/0x4c544f28502018bc93e6c1c5ad84ac09613a5a0a49444284f905a594bca039bf

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
<img width="656" alt="Screenshot 2023-01-08 at 11 58 24 AM" src="https://user-images.githubusercontent.com/85349906/211209092-b750b7f0-60a3-4c29-9ed4-bd4a1fb7a0e1.png">

**Comment by Polypup** [comment]
@grizlydev When you get a chance can you try this exact scenario again. I'm logging more info to get to the bottom of it.

**Comment by Polypup** [comment]
This should be resolved now 👍
