### ISSUE TITLE
[Bug]: mine with a character that has turns  / swap to get exp that has 0 turns [yt video inc.]

### ISSUE THREAD

**Issue by akita066** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#304]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Akita066#5730

### What happened?

I believe this must be reported before, but since you guys work a lot and push updates rapidly, i still wanted to know...

- steps to recreate -
https://www.youtube.com/watch?v=EjRM5rKhPqw

1) have 2 characters (a,b)
* a has 0 turns left and is our main gatherer.
* b is just a vessel that we use only for its turns.
2) go to mines with b, and swap to a. 
* start mining with a (which has 0 turns)

result : using b's turns, a gains the xp. 

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
can no longer switch characters in mines or deepwoods
