### ISSUE TITLE
[Enhancement]:  Finished quests should be removed from QuestList 

### ISSUE THREAD

**Issue by akita066** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#305]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Akita066#5730

### What happened?

Just noticed when you claim your quest reward, your quest would still appear there (as green/finished)
When the quest list has too many elements in it, i wonder what would happen.

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
This is working as intended.
