### ISSUE TITLE
[Bug]: resurrection elixir display LOOT vs OWNED

### ISSUE THREAD

**Issue by akita066** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#306]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What happened?

Seen this issue on Siv's youtube video, shoutout to him ^^, he also notices and talks about the problem.

![image](https://user-images.githubusercontent.com/121979441/211275479-4b93bacf-1b1d-4b56-bb2a-7c4a3d6d5919.png)

Resurrection elixir is orange(fabled) before its in your inventory
also 350 min. crafting is required

![image](https://user-images.githubusercontent.com/121979441/211275706-b3478e33-93a4-4c59-ac88-dded4225e788.png)

Here it is purple(mythic) 
and only 250 crafting is required.

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
this is just because the base item was generated before the rarity change, with a wipe this will resolve itself
