### ISSUE TITLE
[Bug]:  Crafter's guild - Crafting potion with stones of power

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

I tried crafting some potions and bandages and I'm able to put stones of power with my potions. When used, the stones are burned but the potion is minted as usual (no +magic)

![image](https://user-images.githubusercontent.com/8630518/211696101-0b5aa4c6-a53c-415f-ad57-79daeb07cd0e.png)
https://testnet.snowtrace.io/tx/0x379fb3d8090ed77cbdfadb5f27c1b3f2250cf7a903291dfa7195998b4549ed6c

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Yeah, that makes sense. I'll remove stones for consumables.
