### ISSUE TITLE
[Bug]: Crafter's guild - Blueprint drag over blueprint doesn't reset quantity

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When you drag and drop a blueprint with high crafts remaining and drag and drop a low craft remaining blueprint, the max craft option on the bench does not reset. It allows to craft more items than the remaining crafts. See pictures for details.

![image](https://user-images.githubusercontent.com/8630518/211696784-e948d629-c479-4995-93df-918e1fcf9a1f.png)
![image](https://user-images.githubusercontent.com/8630518/211696864-32d0b2eb-f3b9-49b0-9f48-667b004914df.png)
https://testnet.snowtrace.io/tx/0xb01db5a0c38df9d814d2f4c43f9bd3f4bf3cc9925f5c517bc22f3639b3f10607
![image](https://user-images.githubusercontent.com/8630518/211697001-c5e33a72-a7c2-4b33-8ff0-c3b351a6f5d0.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
good find, I'll update 👍
