### ISSUE TITLE
[Bug]: Minor UI issue - Master / Legendary Potion

### ISSUE THREAD

**Issue by SivDraconis** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

When the Master Potion (light yellow color) appears as loot after a battle, hovering over it the name is "legendary potion"

Looking on the toolbar and stash it shows as Master Potion. If I find another I'll try to take a screenshot.

![image](https://user-images.githubusercontent.com/111258598/211935465-54233cde-c3bb-4ff2-a753-78d9c95817f7.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by SivDraconis** [comment]
Another inconsistency - 
![image](https://user-images.githubusercontent.com/111258598/211936119-6acd3922-6ef6-4c49-954e-fa7048d9f049.png)
Legendary Potion (purple) is called "Elixir of Life" when looting.

**Comment by sam-thewise** [comment]
Hey - this is just because the rarity/names were changed after the seed items were created. So the server's data shows the new attributes, but the actual item in the DB uses the old ones. This will be fixed on the wipe.
