### ISSUE TITLE
[Bug]: issue with crafting preview for non blueprint items 

### ISSUE THREAD

**Issue by akita066** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#327]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Akita066#5730

### What happened?

![image](https://user-images.githubusercontent.com/121979441/211946722-eb976db0-43e9-4265-867c-5c96d4295c17.png)

the preview of the combination will be shown if you use the given materials, but not when you replace with other viable ones.

![image](https://user-images.githubusercontent.com/121979441/211947294-314aed69-b8a5-4702-9a6c-c0350469a56c.png)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Sorry, I have no idea what's going on here. Can you explain what you did?

**Comment by Polypup** [comment]
That doesn't look like a blueprint that you have in the main slot there.

**Comment by akita066** [comment]
that is not a blueprint, i can use items that are not blueprints to preview them / see the items they require (if we were to craft them)

> That doesn't look like a blueprint that you have in the main slot there.

**Comment by Polypup** [comment]
How did you put that in the slot? It shows red and cannot be dropped there.

**Comment by akita066** [comment]
> How did you put that in the slot? It shows red and cannot be dropped there.

i just noticed that its not a feature but a bug as well :D just put any  blueprint and then cancel, after that you should be able to drop anything.

**Comment by Polypup** [comment]
When you say remove, you click the remove button and then you can drop any item in there? I've tried this several times and cannot duplicate this.

**Comment by Polypup** [comment]
<img width="795" alt="Screenshot 2023-01-11 at 8 57 40 PM" src="https://user-images.githubusercontent.com/85349906/211957662-8294035f-1415-41f0-965b-049071038e80.png">

Backend that brought down the server. Frontend is bypassing the computed properties for blueprint
