### ISSUE TITLE
[Bug]:  Stash - Withdrawing DCAR & DCAU shows wrong notification

### ISSUE THREAD

**Issue by neothon** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#33]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

#brainiac

### What happened?

![image](https://user-images.githubusercontent.com/89765091/201778277-527ac41f-02d2-4342-b016-91d4ba18c8e8.png)

https://discord.com/channels/887555671963340862/1032911099974127617

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
I couldn't reproduce this. Most probably it's fixed already?

**Comment by Polypup** [comment]
<img width="489" alt="Screenshot 2022-11-14 at 6 31 47 PM" src="https://user-images.githubusercontent.com/85349906/201789838-4f0a0bf9-5b98-42a0-85b5-9c6c1a069705.png">

This was fixed 👍
