### ISSUE TITLE
[Bug]: Turn regeneration problem

### ISSUE THREAD

**Issue by akita066** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#331]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Akita066#5730

### What happened?

Had 0 turns. Got an extra turn (from passive regeneration)
![image](https://user-images.githubusercontent.com/121979441/212197911-f1ea4458-62d1-4df1-8122-bfe706dba0e0.png)

Apparently backend didn't recognize the regen turn.

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Multiple backend servers running
