### ISSUE TITLE
[Bug]: Gathering changes bug

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

There was some changes made to the mines.

It is not possible to enter the mine without a pickaxe. 
It is not possible to search the mines without a pickaxe.
It is possible to finish gathering a node without a pickaxe if it was started by a character with a pickaxe.
It is possible possible to 'keep searching' without a pickaxe if you've finished the gathering of an other character.

![Uploading image.png…]()

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
I think we might disable character switching in the mines as it doesn't really make sense in this scenario.
