### ISSUE TITLE
[Bug]: blueprint item suffix doesn't match item property

### ISSUE THREAD

**Issue by akita066** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#339]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Akita066#5730

### What happened?

![image](https://user-images.githubusercontent.com/121979441/212417010-085ec535-65d7-4d7e-ae43-cebb8ad5bf6d.png)

Crossbow of defense ==> doesn't have the defense modifier.

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
It does have the defense attribute as shown in the popup? Can you explain which part are you referring to? 

![image](https://user-images.githubusercontent.com/89765091/213385498-9da44a28-8e90-48af-9dad-dce7223f7474.png)

**Comment by sam-thewise** [comment]
Yeah the defense is there, its just showing as a normal attribute above, maybe we can move all to the bonus section
