### ISSUE TITLE
[Bug]: Level-up screen

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

If you level-up with a hero that switched out of the fight, the levelling-up screen will show the level-up for the current hero even if he didn't level-up.

1- Select hero near level up
2- Do enough damage to level-up
3- Switch hero
4- finish fight
5- see level-up for wrong hero

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed
