### ISSUE TITLE
[Bug]: Not show quests popup when no hero present

### ISSUE THREAD

**Issue by neothon** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#344]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What happened?

Either disable quests popup if no hero present or enable the "Decline" button

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
