### ISSUE TITLE
[Bug]: Special event level up doesn't refresh HP and turns

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When levelling up with the special event of the shrine. You do not get full hp and full turns from the level up. No level up screen aswell.
![image](https://user-images.githubusercontent.com/8630518/213098720-df5b75fd-a56a-4007-8c3e-b1eacc648851.png)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed
