### ISSUE TITLE
[Bug]: After changing items, health and atack animations don't appear

### ISSUE THREAD

**Issue by Luci13131313** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

luci#8100

### What happened?

A bug happened! I noticed that after changing weapons or items, animations which appears when health reduces or any kind of attack don't appear. Also sometimes using all potions or bandages button that interact with wallet and x button that closes the window, don't work. Refreshing the browser page solved all the bugs.

https://user-images.githubusercontent.com/123016128/213274784-475604a9-a30b-45e1-9518-0b1229c7f1b3.mp4

https://user-images.githubusercontent.com/123016128/213275488-44183885-f0a2-4a8c-a279-6b7f18791794.mp4

https://user-images.githubusercontent.com/123016128/213276177-5ef79af9-d083-4637-9cf5-cf8977d271c4.mp4

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
All these are symptoms of the api resetting.
