### ISSUE TITLE
[Bug]: Limitless cotton and exp

### ISSUE THREAD

**Issue by Luci13131313** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

luci#8100

### What happened?

A bug happened! I tried to search "deepwood" and found unlimited source of cotton and exp without spending energy point. 

https://user-images.githubusercontent.com/123016128/213301816-fc71a008-b15d-4066-8476-b4057fe8414b.mp4

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
This is a false positive - the limits are still in place :)
