### ISSUE TITLE
[Bug]: Hero API Crash - user leveled up from mining 

### ISSUE THREAD

**Issue by Polypup** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

PolyPup

### What happened?

User leveled up and app crashed

### Relevant log output / error message

```shell
Nov 15 08:26:28 load-dcg app/web.1 /app/app.js:2584
Nov 15 08:26:28 load-dcg app/web.1     if (miningResult.expResult.isLevelUp) {
Nov 15 08:26:28 load-dcg app/web.1                                ^
Nov 15 08:26:28 load-dcg app/web.1 TypeError: Cannot read properties of undefined (reading 'isLevelUp')
Nov 15 08:26:28 load-dcg app/web.1     at /app/app.js:2584:32
Nov 15 08:26:28 load-dcg app/web.1     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
```


### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
tagging Paul too as it is related to mining as well.

**Comment by Polypup** [comment]
```
expResult: {
    isLevelUp: true,
    expStats: {
      level: 8,
      exp: 18.05981859453641,
      expNextLevel: 2376,
      levelStatPoints: 19
    },
    expGain: 19
  }
  ```
  
  I'm not seeing any issue here. Very strange. Will keep digging.

**Comment by Polypup** [comment]
Closing this issue as I've leveled up over 100 times through mining resource without issue. 

Added test to mine resource and level up - https://github.com/Dragon-Crypto-Gaming/hero-api/commit/1806c46d503cc5edae99ca8c263fc97d4dc3a75b

Check for `isLevelUp` path - https://github.com/Dragon-Crypto-Gaming/hero-api/commit/c03ebdda343ec582952fc3ac4b8996a2280deaf1
