### ISSUE TITLE
[Bug]:  Resources claim - Items not removed completely from stash after claim

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When withdrawing resources from the stash, you can withdraw the same item multiple times because it they don't completely get removed from inventory (only a portion of it)

Transaction # 1 : https://testnet.snowtrace.io/tx/0x791069344f0b339ef057b47af3e9cc75c6da76ea1364bd5a12b264b50b56feb3
Transaction # 2 : https://testnet.snowtrace.io/tx/0x823eb028229897b6996e73f70f46d9e3b15e43178eea737f7637d3ee6ba70d4c

![image](https://user-images.githubusercontent.com/8630518/213881895-392700fb-2488-4c9b-acb0-c178ede45f35.png)
![image](https://user-images.githubusercontent.com/8630518/213881957-3b59d69c-5da1-4c9d-bdd0-366e47d423ea.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
I don't understand the issue here. Can you please explain how you go about withdrawing items multiple times?

**Comment by Brainiac1830** [comment]
![image](https://user-images.githubusercontent.com/8630518/213884300-63ccaae5-506a-49aa-8885-01cf90df3d06.png)
![image](https://user-images.githubusercontent.com/8630518/213884326-4b0a19ce-c877-4a71-8273-b7c5458a4c50.png)
 If you look at the highlighted part in my screenshots, I have withdrawn 111 darkwood from my stash first transaction. 30 seconds later, I have withdrawn 95 darkwood from my stash again.
 
 If you look at the first screenshot (look at the bottom part of the stash), the items I withdrew are still in the stash on the 2nd screenshot and I can withdraw them again.

**Comment by Brainiac1830** [comment]
Here is an other screenshot showing I was able to claim the same items, many times without gathering more resources.
![image](https://user-images.githubusercontent.com/8630518/213884579-4b7488d0-8240-4965-aa2d-a58674a3e2b2.png)

**Comment by Polypup** [comment]
When was the last time you refreshed the frontend? I'm not able to replicate this. What are you doing to on the frontend to claim these items? Is it just still showing the incorrect number?

**Comment by Polypup** [comment]
It may be a frontend issue that's not being deployed correctly. The backend patch has been deployed and my local machine is working correctly.

**Comment by Brainiac1830** [comment]
https://www.youtube.com/watch?v=2rbv7kieAaE

**Comment by neothon** [comment]
Hey, the video isn't available. 

Oh you deleted it 🙈 

I tried reproducing this but it isn't happening for me on stage or local. Can you record the video and upload again please? 😊

**Comment by Brainiac1830** [comment]
https://youtu.be/cEtOAq6IywQ

It is now not working anymore. Just before I refresh the page, the transactions would go through.

**Comment by neothon** [comment]
sorry, you mean the issue is not there or it isn't claiming anything from the stash?

**Comment by Polypup** [comment]
I think the issue was that you weren't on the upgraded version of our new update. In our new update we provide quantities for our claiming instead of claiming the entire pile of resources. This way a user isn't blocked from interacting with the rest of the map with a pending claim. They'll always be provided with exact amounts from their signature.
