### ISSUE TITLE
[Bug]: Couldn't use potion and died after trying to leave the combat

### ISSUE THREAD

**Issue by Luci13131313** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

luci#8100

### What happened?

A bug happened! I tried to use potion in combat but couldn't manage it. And decided to leave the combat but died after pressing the leave button. 

https://user-images.githubusercontent.com/123016128/213904945-e09ddbaf-687c-4d92-978b-165a20cb9dba.mp4

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Did the prompt for metamask not show up? It looks very quick after you clicked the potion to where you fled.

**Comment by Luci13131313** [comment]
I clicked like 5-6 times before leaving. I couln't upload the full video because there's 10MB limit.

**Comment by neothon** [comment]
Can you try reproducing it. Most likely the metamask prompt was already open, pending and may be hidden behind the window from a previous transaction request.

**Comment by Luci13131313** [comment]
I think I figured it out. It happens when there is another account selected on MM. Sometimes, even if selected account haven't connected to the dapps, it could still open but some bugs appears like this. Sorry to take your time.

**Comment by Polypup** [comment]
resolved
