### ISSUE TITLE
[Bug]: UI BUG 

### ISSUE THREAD

**Issue by akita066** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#355]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Akita066#5730

### What happened?

spam clicking apply stats (the button you hit after distributing your remaining stats) breaks UI

![image](https://user-images.githubusercontent.com/121979441/213933958-1466d87d-a761-4ca5-8fa0-91429ec07060.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
Fixed. Now apply stats button has a loading state now which will make it disabled during applying stats.
