### ISSUE TITLE
[Bug]: combat log button / pin&unpin

### ISSUE THREAD

**Issue by akita066** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#361]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Akita066#5730

### What happened?

not sure if its intended or not but after pressing the combat log button, the ui doesn't shrink if its pinned.

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
I actually kept it like that cause it was pinned. But it makes sense as the notification button should hide it totally.

**Comment by neothon** [comment]
fixed
