### ISSUE TITLE
[Bug]: pending dcar / dcau claim

### ISSUE THREAD

**Issue by akita066** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#362]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Akita066#5730

### What happened?

say you have a pending dcar claim when you have 10k in your stash, then you farm 5000 more, when you go back to the stash and try to claim your dcar it would give you only the first issued amount.  

![image](https://user-images.githubusercontent.com/121979441/216293956-af111906-d783-4453-9741-836bd36a5231.png)

Example: had around 32.5k DCAR, previously pending 17.5k claim. didn't get 32.5k at once. 

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
This is intended for security reasons.
