### ISSUE TITLE
[Bug]: Repair Equipment - Durability Stinks

### ISSUE THREAD

**Issue by andy8810** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

@andy8810

### What happened?

Even though I leveled to 57 via fighting, I think that the durability cost to repair, is a lot. All my gear is now deteriorating and I don't have crafting high enough to repair everything, nor do I have enough materials to repair them either.

Plus, I've now permanently lost two awesome +Magic two-handed staffs that I can no longer use or repair because they hit 0 durability so quickly, without me even noticing.

I do remember in my Diablo days, you used to get some notification or "redish glow" on yourself/gear that alerted you that your gear was damaged and close to breaking.

Maybe that's something we can get integrated here too? Definitely need to do something about equipment that reaches 0 Durability, and the crafting cost mechanisms needed to repair gear. If I'm doing an Attack or Magic build character, I'm clearly not going to devote additional stat points to Crafting. 

The way it stands now in current Beta version, I'm going to have to level up a Crafting Character just to repair my gear for my Magic-based Character because the Crafting requirement to repair my now lost awesome Staff is 250 Crafting Skill Points!

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by andy8810** [comment]
Here's a link to a video of how they repaired gear in Diablo III: 
https://www.youtube.com/watch?v=X2SQkubg08A 

It was pretty simple, it just cost gold to repair, so here in the case of #AurumDraconis, we could just charge DCAR to repair gear. Then you don't have to go around looting and breaking down enough wood just to repair your gear.

**Comment by Polypup** [comment]
Why don't you send them to the repair market for someone else to repair it?

**Comment by andy8810** [comment]
What do you mean?

**Comment by andy8810** [comment]
I found the repair market. Thanks.

How come I do not have access to my full Inventory in the Repair Marketplace? I was only able to put one wand item in the bounty to be repaired. This is starting to feel confusing just to repair gear and get back out to the Plains to fight. This feels like it should be an easier process.

**Comment by Polypup** [comment]
It shows exactly what's damaged in your inventory when in the repair market. If an item is equipped it will not show up there as you cannot send your items off to a contract if they're equipped.

**Comment by andy8810** [comment]
Understood, but if I don't like crafting, I'm now being forced to craft just to repair my gear. Personally, I like to follow the storyline of the game. Also, if I've allocated my stat points to Magic, Defense, and Endurance, the only way I may be able to repair gear is by building up a crafting hero separately just to repair my other character's gear.

**Comment by andy8810** [comment]
Finally, if durability goes completely to zero, is it just dead and never to be used again? forcing me to break it down? 
If so, I just lost a +30 Magic, +6 Defense, +7 Luck staff... That's not cool.

**Comment by andy8810** [comment]
It would be really nice to have notifications and warnings, etc. if your gear is running low on Durability. Checking 13+ pieces of gear after every few turns slows down the gameplay IMO.

**Comment by Polypup** [comment]
> Understood, but if I don't like crafting, I'm now being forced to craft just to repair my gear. Personally, I like to follow the storyline of the game. Also, if I've allocated my stat points to Magic, Defense, and Endurance, the only way I may be able to repair gear is by building up a crafting hero separately just to repair my other character's gear.

You're not being forced to build crafting, you just send it to the marketplace to have others repair your items. 




> Finally, if durability goes completely to zero, is it just dead and never to be used again? forcing me to break it down? If so, I just lost a +30 Magic, +6 Defense, +7 Luck staff... That's not cool.

No, it can be repaired. Can you please provide the name of the item that has these stats and has durability of 0.

**Comment by andy8810** [comment]
Really? Sure. I've got two that are stuck at Zero in my Inventory:
1) Mythical Great Ice Storm Staff of Luck
2) Epic Superior Ice Storm Staff of Magic

**Comment by Polypup** [comment]
> It would be really nice to have notifications and warnings, etc. if your gear is running low on Durability. Checking 13+ pieces of gear after every few turns slows down the gameplay IMO.

Good idea

**Comment by andy8810** [comment]
![Gear-Repair](https://user-images.githubusercontent.com/121076684/216830801-cbfa0d01-3098-40ce-b569-af969b3e2ca7.JPG)

**Comment by andy8810** [comment]
If your gear glowed or radiated red around the box to indicate it was running low. Would also be a good idea to receive a notification on the screen when fighting and when on the main world screen. Something in addition to this so that you are aware of the need to repair.

**Comment by Polypup** [comment]
I see the issue. Give me a few minutes and I'll fix it up. We're checking if the item has a durability stat but when it is 0 it's coming up as false so it's not showing your item for repair.

**Comment by Polypup** [comment]
You should now see gear that has durability of 0 in the repair market. It will take a refresh on your end to see the changes 👍

**Comment by andy8810** [comment]
Awesome. i got them in there for repair now. i'm assuming that when mainnet releases, the downtime to repair will be less? is that the thought?

**Comment by Polypup** [comment]
For sure, people will be sitting there waiting for users to create bounties.
