### ISSUE TITLE
[Bug]: Durability

### ISSUE THREAD

**Issue by Gray1001** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

tmac#8101

### What happened?

I am trying to repair my weapon right now. I have the crafting skill to repair and all materials but when I press repair, durability is still 0 and also the DCAR amount that is needed to repair the weapon is taken. No material change. I have turns.

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Can you provide more information on the item you're trying to repair and what your hero id is.

**Comment by Polypup** [comment]
Was your item the Rare Enchanted Ice Storm Staff of Defense? That has full durability and was repaired correctly.

**Comment by Gray1001** [comment]
Hero id:702 Legendary Superior ice infused bow of attack. Crafting required 100. I have 100 crafting skill and

**Comment by Polypup** [comment]
Okay, let me check.

**Comment by Gray1001** [comment]
Same think happened again. I think this issue hasn't been fixed yet but I wanted to mention. This time game takes both DCAR and fee from metamask but durability still 0. Materials still same amount after the repair. Just letting you know.

**Comment by Polypup** [comment]
Yeah, it's still waiting to be merged.

**Comment by Polypup** [comment]
It was just merged. Can you please keep me updated on whether this is happening every time your repair or just on a particular item?

**Comment by Gray1001** [comment]
I tried few items to repair. different kind. During repair, It takes fee and material but durability did not change and the screen was disaapeared. Only an empty map can be seen and ı can not see the writing on the map or do anything. I have to refresh the page. After I refresh, durability is seen full.
