### ISSUE TITLE
[Bug]: Equipment bonus does not add to skill

### ISSUE THREAD

**Issue by ghostfaceavax** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#367]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

GhostFace#7161

### What happened?

Clothing and weapon equipment does not add bonus skill points. For example, having 350 in crafting skill to repair fabled items is not the same as have 100 in skill plus 250 craft bonus from equipment.

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Are you saying that it didn't work? I don't understand how to replicate this issue. Can you explain what exactly happened?

**Comment by ghostfaceavax** [comment]
Yes, when i tried to repair a weapon that required 350 Craft stat, and i got a message saying that i did not have enough skill level for that repair. my Craft level at that moment was 230 and 121 bonus from equipment.

**Comment by ghostfaceavax** [comment]
i had to use a amnesia potion to change my Craft skill to 350, the fact that i had bonus from equipment did not allow me to craft.

**Comment by ghostfaceavax** [comment]
*Did not allow me to repair

**Comment by Polypup** [comment]
<img width="410" alt="Screenshot 2023-02-07 at 5 37 46 PM" src="https://user-images.githubusercontent.com/85349906/217383308-fa454882-5a01-482b-935d-4d7f70bd9f90.png">
<img width="382" alt="Screenshot 2023-02-07 at 5 39 50 PM" src="https://user-images.githubusercontent.com/85349906/217383318-7276d195-3c5d-4a07-acee-795baca79661.png">
<img width="281" alt="Screenshot 2023-02-07 at 5 40 05 PM" src="https://user-images.githubusercontent.com/85349906/217383330-e381c7aa-9afe-4757-bd5b-a518c73bc11d.png">


I'm not able to replicate this bug. I was able to repair in both the crafting menu and the repair shop with 100 base crafting and 150 crafting on my equipment. The item I was repairing required 250 crafting.

Where exactly did you face this issue? Was it the crafting menu repair (self repair)?

**Comment by Polypup** [comment]
I'm not able to replicate this or it's been fixed.
