### ISSUE TITLE
[Bug]: UI - Repair Market Place - Mouse over pop up not big enough

### ISSUE THREAD

**Issue by Lazerthelazy** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Lazer_the_lazy#0343

### What happened?

Last entry of inventory items is outside the box.
![dcg2](https://user-images.githubusercontent.com/119103707/216843375-173324ff-24d7-49b5-a19e-11d8c9c09822.jpg)

windows firefox 1920 x 1080 100% zoom

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed
