### ISSUE TITLE
[Bug]: Re-selecting hero shows more stamina 

### ISSUE THREAD

**Issue by connorbode** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

coconaut#2900

### What happened?

I was messing around trying to get more stamina. I clicked the character select button.

![image](https://user-images.githubusercontent.com/1156049/202509924-53272ed1-bf98-4379-9450-eb0839f5db60.png)

Then deselected my hero

![image](https://user-images.githubusercontent.com/1156049/202509995-a9c01a53-a4ff-4b96-ab6e-0954deed57fb.png)

Then selected my hero

![image](https://user-images.githubusercontent.com/1156049/202510101-41f207a8-b7f3-4667-b907-7dcedcf992cf.png)

And my stamina was increased to 10. 

On a separate occasion, I performed these actions and my stamina was partially increased from 0 to 6.

On one of these occasions, the game started glitching out when I was trying to do things that required stamina, such as fight monsters or collect resources. I was unable to actually perform the stamina-consuming action, and IIRC the game gave a blank message? After I went to the healer, the issue was resolved.

I'm still learning about the stamina system, so this could partially be expected behavior.. I am unsure. 

Worth noting that I am not able to reliably reproduce this issue.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output / error message

```shell
Browser is Chromium build on linux, not Chrome official
```

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
tried reproducing but was unable to. Need to follow up with @connorbode

**Comment by neothon** [comment]
Verified again. Unable to reproduce this.
