### ISSUE TITLE
[Bug]: Weapons Breaking Too Often.

### ISSUE THREAD

**Issue by andy8810** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

@andy8810

### What happened?

I have been trying my best to level from 59 to 60. While I understand I am at a higher level of play, I currently have NINE (Yes, Nine) staffs and wands in the Repair Marketplace, waiting for someone to hopefully repair them. It has taken me well over 2 hours now to level up. While I understand that may be the intent, slow leveling down and get people focused on the crafting side as well as other features of the game, I become stuck as a Mage who can't keep their weapons durable for more than a fight or two, then, because I do not have +Attack, but rather +Magic stat points, I am unable to do any more the ~50 Damage points using my fists. This makes for long and boring battles, for nothing other than I want to hang in there and win the fight, so that I can gain the experience points and not lose a fighting turn. Can something be done to improve the longevity of wands and staffs so that I don't end up being so defenseless when their durability runs out?

Thanks for allowing me to provide this input. Love helping out on this project! #AurumDraconis

Best Regards,

Andrew

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Closing this issue. This is balancing feedback and would good to be discussed on discord.
