### ISSUE TITLE
[Bug]: Pending DCAR Transaction Although Nothing Pending

### ISSUE THREAD

**Issue by andy8810** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

@andy8810

### What happened?

Stuck unable to claim DCAR and DCAU from the stash. Says I have a pending DCAR transaction when I don't see anything pending in my Metamask. Needs reset? I've tried loggin out and back in as well as closing window and reopening.

Thanks for the help! :)
![issue pending dcar](https://user-images.githubusercontent.com/121076684/217123265-2164c7cf-dbbb-4f13-bf7f-5b9001c6f0ea.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
@andy8810 hey, so if you have a pending claim from before, it will automatically claim that amount. It just shows the message on top that you have a pending claim. But when you try to claim, it will auto claim the previous amount. I will try to improve the message here to avoid confusion

**Comment by neothon** [comment]
Ahhh, did you mean you are stuck claiming DCAU? If you have a pending claim of any of the token, you need to claim that first to continue. I have improved the message being shown so as to avoid confusion 
![image](https://user-images.githubusercontent.com/89765091/217170994-f26d1a48-93fa-453a-96d1-715b3c852d7d.png)
