### ISSUE TITLE
[Suggestion]: Durability Sensor on Weapon while Fighting?

### ISSUE THREAD

**Issue by andy8810** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#376]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

@andy8810

### What happened?

Just a thought here, to maybe add the durability bar to the weapon on the fighting screen? In general I'm having a hard time gauging if my hero's weapon is going to last through a mob fight. If I come across a Mob that is way over my head in HP, I will just flee as I know my weapon is not going to make it through the fight. Unfortunately, I can't really see or tell if my weapon will last the entire fight, or run out of durability half way through a fight. Kind of frustrating because I enjoy taking down those large mobs with super high HP. Unfortunately, I am just fleeing now when I come across them because I don't want to sit there and hit them with my fists for 30 minutes.

Thanks for understanding. Hopefully we can find a way to improve the durability of weapons.

Best,

Andrew
![durability sensor - while fighting](https://user-images.githubusercontent.com/121076684/217722326-edf75edb-806b-428e-9c0c-bec44c36a0fa.JPG)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
What type of weapons are you fighting with? Are these Mythical weapons. At your rank, it's probably what you need. Having something lower means you need to hit the crafters guild or marketplace to get a better weapon.

**Comment by andy8810** [comment]
I've got Mythicals and just got a Fabled. At these mid 50s-60s+ levels, if you don't have fabled gear, you seem to have a hard time getting more than 5-7 fights with mythical staffs. My Fabled staff got me 11 turns. 

Basically, what I'm getting at here in the above screenshot, is I cannot see the durability of my weapon, the one item that degrades the quickest. It would be nice if while fighting, I could see if my weapon is going to last the entire fight or not. 

If I run into a mob that is way above my HP, and I know my weapon is not going to make it through the fight, then I would then know it's probably best to flee and repair it, rather than try to take it down with my fists. I only do around 50 damage per hit with my fists because I have my stat points in +MAGIC, not +ATTACK.

**Comment by Polypup** [comment]
fixed
