### ISSUE TITLE
[Bug]: invalid amount for stashed dcar

### ISSUE THREAD

**Issue by ghostfaceavax** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#377]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

GhostFace#7161

### What happened?

I cannot claim dcar rewards from stash. i get error message invalid amount for stashed dcar

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by ghostfaceavax** [comment]
![Screenshot (602)](https://user-images.githubusercontent.com/122186497/218286898-ce9e02fe-c655-4692-af77-716141c9547c.png)

**Comment by Polypup** [comment]
I have that particular error fixed in my current branch. Due to the amount we need to compare bigNumbers instead of floating point numbers. You will also not be able to claim this amount due to our daily minting limit. I'll have to talk to @sam-thewise on the best way to approach this.

**Comment by Gkashh** [comment]
I also have this issue 
How can it be resolved

**Comment by Polypup** [comment]
It's waiting to be merged by the team.

**Comment by Polypup** [comment]
Fixed
