### ISSUE TITLE
[Bug]: When listing blueprint, image on sell screen is of item, not of bluprint

### ISSUE THREAD

**Issue by SlayerVan** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#378]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Van gogh

### What happened?

When listing blueprint, image on sell screen is of item, not of blueprint. Also i noticed when the sell is being approved, if i hover over another item the title of the sell screen changes. Not a huge deal, but can be confusing. 

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Duplicate and intended 👍
