### ISSUE TITLE
[Bug]: No warning on session expiration

### ISSUE THREAD

**Issue by connorbode** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#38]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Contact Details

coconaut#2900

### What happened?

**What I experienced**

I had the game open in a browser tab overnight, possibly longer. I came back to the game, applied some stat points (specifically added 10 to endurance), tried to do some other actions. I can't recall exactly what happened, but it was not working to interact with the game. 

When I did a browser refresh, the game asked me to sign a message. I logged in and noticed that my 10 stat points I had added to endurance were unspent. The game continued to work.

**What I assume happened**

Presumably my authentication token at the server had expired. The game did not give me any warning of token expiration, so I was confused. When I refreshed the browser, the game asked me to sign in & everything functioned properly.

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
- [ ] track sessions which shows a popup that the session has expired.
- [ ] provide button to take the user to the login screen

This is a good flow so the user knows what has happened
