### ISSUE TITLE
[Bug]: Can repair Shoddy if it's non-zero durability, but doesn't do anything

### ISSUE THREAD

**Issue by BoltTouring** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#380]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Siv

### What happened?

Tried to repair a Shoddy belt. Transaction went through, but durability did not go up
![image](https://user-images.githubusercontent.com/111258598/219336264-2d1f10eb-f6ee-4069-9cd6-ef9fe92d385d.png)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Hey @SivDraconis,

Did this happen for every item that you tried to repair? I can see that you had enough resources and enough crafting.

**Comment by BoltTouring** [comment]
Fixed on unequip of any item. But still kind of weird it doesn't update.

**Comment by Polypup** [comment]
I see, so it healed but it didn't get updated on the frontend. I'll take a look and put a fix in 👍

**Comment by BoltTouring** [comment]
https://www.twitch.tv/videos/1739719027?t=00h01m29s - check it out

**Comment by Polypup** [comment]
Perfect, thank you ❤️

**Comment by Polypup** [comment]
Fixed
