### ISSUE TITLE
[Bug]: Repair Market - 'Can Craft' only looking at skill point

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When on clicking on 'can craft' in repair/crafting market, you'll only be able to see the items you can craft with skill points attributed, not items skill point.

![image](https://user-images.githubusercontent.com/8630518/219906300-b7566386-d31d-45bb-9472-8304c4c8e231.png)
![image](https://user-images.githubusercontent.com/8630518/219906309-f6a0fa05-efc9-4b90-9d5a-c64d22226620.png)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
