### ISSUE TITLE
[Bug]: fighting animations and log stopped.

### ISSUE THREAD

**Issue by ElBirdo** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

ElBirdo

### What happened?

While in a fight I closed laptop and came back roughly a couple hours later.  I opened the laptop and resumed the fight.  I click attack and dame is done but not displayed and no animations are performed.  The activity log pinned to top also did not update.  This all continued for every turn.  I obviously had to refresh browser to fix.

### What browsers are you seeing the problem on?

Firefox

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
The session had expired.
