### ISSUE TITLE
[Bug]: leveling up

### ISSUE THREAD

**Issue by ghostfaceavax** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#387]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

GhostFace#7161

### What happened?

After leveling up with my hero. I recived the level up pop up notification but i decided to ignore it and kept gathering. I came across a issue, it would reset my experience and the level up message would come out again. Every time i gained experience from gathering it reset my exp. I kept gathering until the resource was depleted and realized i gained no experience and did not level up because i didnt stop to use my skill points. 

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
