### ISSUE TITLE
Enhancement: Fix HP after using a bandage

### ISSUE THREAD

**Issue by s1lv3rback** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#389]
HP after using a bandage goes out too many decimal places. 

![image](https://user-images.githubusercontent.com/121063058/221434184-505384a5-cffe-4d93-9a30-5fe0f24b793e.png)

**Comment by s1lv3rback** [comment]
Continues into battle

![image](https://user-images.githubusercontent.com/121063058/221434236-8b6e625d-4ebe-4a72-9d0c-4462185cc283.png)

**Comment by Polypup** [comment]
fixed
