### ISSUE TITLE
[Bug]: cannot use bandage when only 1 in inventory

### ISSUE THREAD

**Issue by s1lv3rback** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#390]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Contact Details

kyrpto

### What happened?

Unable to use bandage when I only have 1 bandage in inventory. Click on the bandage or the use all button and nothing happens. 

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by s1lv3rback** [comment]
Cannot use while in battle either

**Comment by neothon** [comment]
I had 5 bandages and used up 4 to keep just 1. The last one also worked? How did you get that 1 bandage?

**Comment by Polypup** [comment]
This should be fixed now with latest patch
