### ISSUE TITLE
[Bug]: No level up notification if you level up from Bard Song

### ISSUE THREAD

**Issue by s1lv3rback** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

kyrpto

### What happened?

 No level up screen if you level up from Bard Song

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
