### ISSUE TITLE
[Bug]: Missing image - Holy Light Mail Leggings

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

Missing image for this item : 
![image](https://user-images.githubusercontent.com/8630518/221721737-c745089f-844e-45f7-843d-50589a91b97f.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
