### ISSUE TITLE
[Bug]: UI not grey when out of turns

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When your hero is out of turn, the UI doesn't turn grey on 'plains', 'mines' & 'deepwood'.
![Screenshot 2023-02-28 091507](https://user-images.githubusercontent.com/8630518/221744930-b8da4e83-81c5-4ebf-9b32-fc7a8b2c815a.png)

However if you have turns available but no pickaxe for the mines, it will be grey.
![image](https://user-images.githubusercontent.com/8630518/221744836-624de956-5881-42ad-9611-c9df3254630f.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
