### ISSUE TITLE
[Bug]: Mining - Use Bandage to mine

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

1. Start mining with character who has a pickaxe
2. Switch character with no weapon equipped.
3. See 'Use bandages' button to mine
4. Read 'You use your first (ouch)' in the activity log
![Screenshot 2023-02-28 084332](https://user-images.githubusercontent.com/8630518/221746479-9ad9af06-ae28-4c9e-8aa4-8068f2c327ee.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
