### ISSUE TITLE
[Bug]: Health point with decimal

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When equipping items that give a number of HP that isn't a factor of 10, you can get decimal numbers in your health bar after using potions.

1. Equip item that give +63 health / +75 health.
2. Get low HP
3. Use 1x health potion that would end up with a decimal number.
![Screenshot 2023-02-28 092605](https://user-images.githubusercontent.com/8630518/221746288-a735253a-142e-4883-9289-c86b1f81da2a.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
