### ISSUE TITLE
[Bug]: Cotton - Shows 'smelt : cloth' on hover

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When hovering over the cotton resource, you can see 'smelt : cloth' in the description. Replace smelt by 'crafts into' so it's a more generic term that is usable by all items.

![Screenshot 2023-02-28 100853](https://user-images.githubusercontent.com/8630518/221746928-c61e4149-2e1d-4465-a8c9-7874aa2fa271.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
