### ISSUE TITLE
[Bug]: No resources when breaking down broken items

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When breaking down an item that is completely broken, you do not get resources. In the screenshot I just broke down 2 common items (blockchain transaction) and got nothing back. No warning that broken item would not give resources.

'Warning : Broken items will not give resources when broken down'

![Screenshot 2023-02-28 103736](https://user-images.githubusercontent.com/8630518/221747503-97ced817-ff1c-4465-a97d-3a8d199a0316.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Brainiac1830** [comment]
Just a little update. Any item from you inventory (burn transaction) will not give items, while stash items will do.

https://youtu.be/PLl7y1sYbTs

**Comment by Polypup** [comment]
fixed
