### ISSUE TITLE
[Bug]: Game chat - Timestamp is 'NaN - Years ago'

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When typing something in chat, the timestamp I received was 'NaN - Years ago'. Persisted upon closing the chat windown, but updates after page refresh. 

![Screenshot 2023-02-28 104818](https://user-images.githubusercontent.com/8630518/221747824-df703c9a-6341-4068-9a43-ef99cb8360e2.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
