### ISSUE TITLE
[Bug]: Resurrection/healing issues

### ISSUE THREAD

**Issue by SivDraconis** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

- One hero dead, one hero damaged. 
- Go to Healer with dead hero, try to resurrect - just spins
- Switch to damaged hero and try to heal - just spins
- Refresh - can heal as normal if trying to heal damaged character, but resurrection still doesn't work

See video (uploading now): https://youtu.be/zoOQclrmc0o

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Renter address issue. Investigating still

**Comment by Polypup** [comment]
@SivDraconis I'm having difficulties replicating this. I've done the following. 
- Created 2 heroes
- Both heroes are rented as seen in your example
- Damaged 1 hero
- Killed another hero
- Logged In again
- Toggled the dead hero
- Entered the healers hut
- Both the resurrect and healing both work

Is there anyway you can right click, click `inspect`, and then click `console` while you're in the healers hut. This will show any errors that popped up on the frontend.

**Comment by Polypup** [comment]
I was able to rent the same heroes as the example provided in the video, use the same stats, login and replicate exactly without issue. It almost appears that there may have been an rpc issue on fuji testnet at the time of this bug. There are no error logs on the backend either.

**Comment by Polypup** [comment]
🤔  Metamask error. Something is going on with the rpc. Any idea what rpc you're connected to? 

Also could you click the Object arrow under the metamask error and send a pic over. Thank you for the help.

**Comment by SivDraconis** [comment]
![image](https://user-images.githubusercontent.com/111258598/203225257-7aee92bf-a333-4d83-b15c-cc9d7df3f024.png)

RPC: https://api.avax-test.network/ext/bc/C/rpc

**Comment by SivDraconis** [comment]
![image](https://user-images.githubusercontent.com/111258598/203225936-ab6a59ad-2715-4db5-8e85-d43e90024686.png)

Another

**Comment by Polypup** [comment]
Ahh! Not enough DCAU to make the transaction. We need to provide more info that you ran out of DCAU

**Comment by SivDraconis** [comment]
Huh. I didn't realize. Yeah it shouldn't just spin - would be better to throw an error. I wonder if it's also an issue if you go to the healer with a character that only needs say .5 DCAU of healing when you have .6 in your wallet and then switch to a character that needs more than .6.

**Comment by Polypup** [comment]
Yeah, I agree. I'm going to add a detailed message on the status of your DCAU if it's too low.

**Comment by SivDraconis** [comment]
Yep - that's the issue. I filled up with DCAU at the faucet and I can't recreate the bug.

**Comment by Polypup** [comment]
Added messages for the user if they do not have enough dcau to resurrect or heal:

https://github.com/Dragon-Crypto-Gaming/aurum-draconis-prototype/commit/97c4161e1c9a869a228af53df76755a9b12529b9
