### ISSUE TITLE
[Bug]: Health shows as a decimal

### ISSUE THREAD

**Issue by BoltTouring** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

After using bandages, my health shows as a decimal and stays that way through fights.
<img width="238" alt="Screenshot 2023-02-28 at 5 30 33 pm" src="https://user-images.githubusercontent.com/111258598/221833454-7440937e-2f92-4395-ae4a-a5d482686c0f.png">

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed

**Comment by BoltTouring** [comment]
@Polypup - also showing up during battle
![image](https://user-images.githubusercontent.com/111258598/221994297-d79cfe70-837c-440b-8d01-d84d284e23cb.png)
