### ISSUE TITLE
[Bug]: Crafting - Stones not giving the right stat to item

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When trying to craft items, the amount of +magic displayed on the stone doesn't reflect properly on the item. It is still % based I think.

1. Put item with base +magic.
2. Add +3 stone of power
3. See incorrect amount

![Screenshot 2023-03-01 121353](https://user-images.githubusercontent.com/8630518/222046657-9187beaf-8429-480b-b2b1-d2619a5f7448.png)

![Screenshot 2023-03-01 121415](https://user-images.githubusercontent.com/8630518/222046586-10446a95-0642-4be0-b118-47638913246e.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
