### ISSUE TITLE
[Bug]: Claiming resources - Resource did not appear in inventory.=

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

I tried to claim iron ore by itself. Transaction succeeded and notification tab showed 'You have successfully claimed 1 resource' but I did not get it in my game inventory.

When opening the forge after refresh, still no item. Shouldn't the forge inventory be loaded by looking at the user's blockchain inventory instead of server?

Transaction :
https://testnet.snowtrace.io/tx/0x3dd19f5b12998e36dd69731097fb0dd1100aaa5798e32ab792ec6ff95eaea6ad
Inventory : 
![image](https://user-images.githubusercontent.com/8630518/222047188-21bec3e3-7ea2-4c4d-93c5-9b6cb500be0b.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Pushed a fix a few hours ago for lagging rpcs. We check the latest block number and compare it to the user's block number and wait for our server to catch up. Please reopen if this happens again. I checked your address and saw your claimed more and burned some within the last few hours.
