### ISSUE TITLE
[Bug]: Leaderboards - Kills & Close quarter combat not showing

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When opening the leaderboards, the 'kills' and 'close combat mastery' aren't getting tracked properly... showing 0

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed.

close quarters hasn't received any kills from what I can tell. The final hit update was being overwritten by an exp hero stat update. It's now tracking kills and last hit on mastery.
