### ISSUE TITLE
[Bug]: Starter Kit - Item tooltip under the loot window.

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

![Screenshot 2023-03-02 112421](https://user-images.githubusercontent.com/8630518/222331471-a70fabcc-c0b7-4b68-b996-92ab42f71cc9.png)

When you receive items from loot chest or starter kits, you can't really see the tooltip from these items because it is shown underneath the loot received page.

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
