### ISSUE TITLE
[Bug]: Burn NFT on being broken into smaller parts.

### ISSUE THREAD

**Issue by neothon** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#41]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What happened?

![image](https://user-images.githubusercontent.com/89765091/203560578-02d2a986-4754-4fd0-8fe5-ecd0346d0389.png)

On breaking equipment down to individual resources, the resources go to the stash and the equipment NFT should be burned. 

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Smart contract is completed, just waiting on review: https://github.com/Dragon-Crypto-Gaming/load-contracts/pull/15

**Comment by sam-thewise** [comment]
Smart contract was reviewed and merged a bit ago - just need to make sure  it's working through the server/front end :)

**Comment by Polypup** [comment]
fixed
