### ISSUE TITLE
[Bug]: nftIds undefined

### ISSUE THREAD

**Issue by Polypup** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

PolyPup

### What happened?

<img width="661" alt="Screenshot 2023-03-02 at 12 22 45 AM" src="https://user-images.githubusercontent.com/85349906/222338449-6ef4c16f-ec20-425c-8f2b-51f482d0645e.png">

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
Seems like nftIds was not passed in the post request. Added a check for nftids not being null.  Any idea how this happened? Like what were the steps?

**Comment by Polypup** [comment]
I have no idea. There wasn't much there. Maybe an rpc fault.
