### ISSUE TITLE
[Bug]: Starter Kit - 1x Double Loot & 3x No potions

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When I opened my Starter Kits, I got double loot in my stash from the Crafter Starter Kit.

I also only receive 5 of each potions when I should of received 20 of each.

https://www.youtube.com/watch?v=quvzVOtGxP0

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
Hey buddy! So when you said double loot items as in two exactly same items? From the video it seems like you opened a crafter's kit before once and had those in the stash? Not duplicate items.

Did you open any crafter's kit before? Or had your hero reset or something?

Regarding the popup thingy, yes that's already fixed and is awaiting merging :)

Regarding the 5 potions. At present every loot box gives you 5 of each of those two potions. I need to check the original tweet when we released the starter kits to double check this.

**Comment by Brainiac1830** [comment]
> Hey buddy! So when you said double loot items as in two exactly same items? From the video it seems like you opened a crafter's kit before once and had those in the stash? Not duplicate items.
> 
> Did you open any crafter's kit before? Or had your hero reset or something?
> 
> Regarding the popup thingy, yes that's already fixed and is awaiting merging :)
> 
> Regarding the 5 potions. At present every loot box gives you 5 of each of those two potions. I need to check the original tweet when we released the starter kits to double check this.

From opening 1x of each chests (4 total) I got :
2x Crafter Kit (2 different items of each armour type)
1x Warrior
1x Mage
1x Ranger
5x Healing Potion
5x Greater healing potion

**Did you open any crafter's kit before? Or had your hero reset or something?**
No

Just happened to Andy on his discord livestream when opening the chests

**Comment by neothon** [comment]
oooo I will look into it. Thanks! :)

**Comment by neothon** [comment]
yes, the crafter's loot is being minted twice. Thanks. I think while testing I had so many crafter loot items in the stash I didn't realise this was happening haha

**Comment by neothon** [comment]
@Brainiac1830 can you check again if this is happening? I think a fix was already pushed in previous merges. Minted a couple of crafter's chest for you to test.

**Comment by Brainiac1830** [comment]
> @Brainiac1830 can you check again if this is happening? I think a fix was already pushed in previous merges. Minted a couple of crafter's chest for you to test.

Did not get anything minted to my account! 
![image](https://user-images.githubusercontent.com/8630518/223964158-41201b29-7e17-43a4-a6de-b5d058a324f8.png)
0xCB4032379CAF07Bc41C7cF2A10763f99a170c2Ed

**Comment by neothon** [comment]
wait, I did mint to this address only. Let me check


Oh it never went through haha 
![image](https://user-images.githubusercontent.com/89765091/223967303-683d89dc-eed7-4744-a710-ae1741133701.png)


Should be there now 👍🏼

**Comment by neothon** [comment]
just make sure your stash doesn't have similar items already to avoid any confusion.

**Comment by Brainiac1830** [comment]
Everything worked properly for the items. The resources didn't seem to appear in stash

**Comment by neothon** [comment]
fixed. Generating no duplicates and ensuring correct amount of resources/consumables added to stash.
