### ISSUE TITLE
[Bug]: Error msg when trying to heal in healers hut

### ISSUE THREAD

**Issue by s1lv3rback** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#412]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

kyrpto

### What happened?

A bug happened!
![image](https://user-images.githubusercontent.com/121063058/222439294-f5d5c7f1-183a-4349-8246-82cf08d608fa.png)
![image](https://user-images.githubusercontent.com/121063058/222439448-9999effc-de37-4618-924e-b3797f17259b.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
