### ISSUE TITLE
[Bug]: Daily quest level-up - No level-up screen

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

I leveled-up with my daily quest and didn't get the 'new' level-up screen. Just this : 
![image](https://user-images.githubusercontent.com/8630518/222615042-768a5f05-dfeb-4b29-8ddd-b5ee63f69518.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
