### ISSUE TITLE
[Bug]: Healer's hut - Amount of DCAU needed not shown

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

![image](https://user-images.githubusercontent.com/8630518/222616911-8e2f25cc-1d0d-46e5-8619-54ab07f87d2d.png)

When trying to resurrect in the healer's hut, I was told I didn't have enough DCAU to resurrect, but it didn't show the amount I had to pay.

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
