### ISSUE TITLE
[Bug]: Plains - No tooltip in the plains for some leather items

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When looting leather items in the plain, you do no get a tooltip for it compared to when it is in inventory.

![Screenshot 2023-03-03 114539](https://user-images.githubusercontent.com/8630518/222630832-68118223-795b-4a78-bf4d-4062c91c8cac.png)

![Screenshot 2023-03-03 122205](https://user-images.githubusercontent.com/8630518/222630938-86d750b7-cb9b-4afd-8e77-fbe7d22f9d27.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
