### ISSUE TITLE
[Bug]: Unknown - Hero reset to level 1

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

I was using my mining actions on 2 different characters and feeding the experience to my gatherer. It happened 3 times that after switching back to my action hero, he kept the stats, hp, turn, exp of my gatherer. After refreshing the game, my hero was now level 1 with no skill points allocated, no experience, with 10 turns available, items were still on him.

Here is a screenshot of me trying to unequip items with health points but not being able to because the character now has only 100 hp.
![Screenshot 2023-03-03 112517](https://user-images.githubusercontent.com/8630518/222631471-6c7ebec0-c2c8-4225-a9e0-c51c0cd62392.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
I need to tune into your next livestream and see how you do this. I tried replicating for the last hour and cannot. I'm unsure if this has been resolved now that the unique index has been added to the db.

**Comment by Brainiac1830** [comment]
I haven't found a way to 100% replicate this, but will keep trying to!

**Comment by Polypup** [comment]
This should be resolved now.
