### ISSUE TITLE
[Bug]: Fix decimal health during combat

### ISSUE THREAD

**Issue by neothon** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#418]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What happened?

![image](https://user-images.githubusercontent.com/89765091/222816300-5c02c713-c86f-4e57-9016-f2d7a6d77b00.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
