### ISSUE TITLE
[Bug]: Repair - No error prompt when not enough DCAR

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When attempting to repair an item but you do not have DCAR, there is no message popping up. Just no transaction appearing. It was a little confusing why it wasn't working. 

https://www.youtube.com/watch?v=WmWdutFxeT0

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
