### ISSUE TITLE
Breakdown Gear Gave Nothing

### ISSUE THREAD

**Issue by andy8810** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#420]
Not sure if this is a bug or not, but I broke down two weapons, that I thought I was going to get some Iron Bars from. Instead, I got nothing. They are not in my stash or my inventory. Strange... 
![wipe - issue breakdown](https://user-images.githubusercontent.com/121076684/222873995-0669ebb0-2da6-45f8-8df3-e6b8be565df5.png)

**Comment by Polypup** [comment]
fixed
