### ISSUE TITLE
[Bug]: Deepwood - Iron wood not showing up in stash

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When gathering Iron Wood, the items do not appear in the stash. There's probably a supply of 0 on the blockchain for this item.

Will try to get a screenshot / recording of me gathering it and checking stash after.

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
