### ISSUE TITLE
[Bug]: Can apply skill points

### ISSUE THREAD

**Issue by ghostfaceavax** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#422]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

GhostFace#7161

### What happened?

anytime i apply skill points my hero disappears 

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by ghostfaceavax** [comment]
https://user-images.githubusercontent.com/122186497/222875716-274e655d-f5a5-477a-9c86-da9f4a3b0db8.mp4

**Comment by neothon** [comment]
Can you please clear your localstorage and try to reproduce this again?

**Comment by ghostfaceavax** [comment]
https://user-images.githubusercontent.com/122186497/222907646-dcaac3dd-fa0e-4fd5-ade5-de5665dcd678.mp4

**Comment by Polypup** [comment]
This appears to be resolved. We'll open again if this persists.
