### ISSUE TITLE
[Bug]: Error on Loot Chest tab

### ISSUE THREAD

**Issue by BoltTouring** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#424]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Contact Details

Siv

### What happened?

Clicked on loot chest tab in my equipment and get the following error

![image](https://user-images.githubusercontent.com/111258598/222929301-51bac213-2375-4fea-a389-61fc868e1bec.png)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by BoltTouring** [comment]
Might have been during a deployment. I got forced to login again and seems to be working.

**Comment by neothon** [comment]
Tried reproducing it multiple times but couldn't. I will still keep a look out for it :)
