### ISSUE TITLE
[Bug]: Level-up - Level-up from shrine of experience doesn't refresh health + turns

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

![Screenshot 2023-03-08 160220](https://user-images.githubusercontent.com/8630518/223656747-3738088c-3a11-44ce-b930-23fd41309c59.png)

When you level from the event 'shrine of experience' your turns and health does not refresh.

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
