### ISSUE TITLE
[Bug]: Upgrade durability - Can click on the '+' icon to upgrade durability on items in the marketplace

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

![image](https://user-images.githubusercontent.com/8630518/224870570-a967beb5-cb6a-4cc2-9682-91c3fb3bf1f0.png)

!. Go in marketplace
2. fHover on item
3. Click '+' to upgrade durability
4. Button does nothing, but not error msg.

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
