### ISSUE TITLE
[Bug]: Durability increase allows negative numbers

### ISSUE THREAD

**Issue by BoltTouring** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#429]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Siv

### What happened?

First type a positive number, then put a minus sign in front
![image](https://user-images.githubusercontent.com/111258598/224872624-e9a76b4d-d3b6-49d7-9a90-cf3c5973f097.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
