### ISSUE TITLE
[Bug]: Breaking down an item with increased durability gives no resources

### ISSUE THREAD

**Issue by BoltTouring** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

Increased durability to max. Broke down item. Received nothing!
![image](https://user-images.githubusercontent.com/111258598/224873596-d8223843-99c6-4b04-8f3a-05eb96c5b732.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Brainiac1830** [comment]
Not just items with increased durability, any items.

**Comment by Polypup** [comment]
Yeah, I found the bug. We do a check for the owner of the item but since it's burned prior to us doing the check it wasn't passing that part of the code. It's waiting for merge.

**Comment by Polypup** [comment]
fixed
