### ISSUE TITLE
[Bug]: UI is broken on items with zero durability

### ISSUE THREAD

**Issue by BoltTouring** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

The upgrade durability pop-up has no information for items with zero durability
![image](https://user-images.githubusercontent.com/111258598/224873952-f7e058eb-4f4e-49fe-a1e8-ae6ecceda2ea.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by BoltTouring** [comment]
Another 
![image](https://user-images.githubusercontent.com/111258598/224874151-25584f00-13b1-4ba7-8826-ac1e7572ec5c.png)

**Comment by Polypup** [comment]
fixed
