### ISSUE TITLE
[Bug]: Potions - No healing if window is closed before transaction goes through

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

If you try to heal up and your browser closes before the transaction goes through, you will not be healed once you're back in the game but your transaction to burn a potion will have gone through and you lost a potion.

1. Enter a fight (and be low hp)
2. Use potion
3. Exit game
4. Log back in after transaction is approved
5. Did not get healed, but NFT is burned.

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Need to add sync event for consumable burn

**Comment by Polypup** [comment]
fixed
