### ISSUE TITLE
[Bug]: Amnesia Gas - Not showing a disabled tooltip when dead

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

![image](https://user-images.githubusercontent.com/8630518/224880136-d5a5955d-1543-4233-9018-3c93db361189.png)

When dead, all the other potions are in a 'disabled' status except 2 potions.

1. Resurrection potion (fine)
2. Amnesia Gas (not fine since you can't use it while dead)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
