### ISSUE TITLE
[Bug]: Death - Able to use potions while dead

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

How to heal your dead hero (still needs to be resurrected). 

1. Select alive hero
2. Open inventory
3. Select dead hero
4. Go to potions tab
5. Click on potion
6. Accept transaction
7. Get healed (still dead)

https://user-images.githubusercontent.com/8630518/224881007-ac2de1a2-3cce-440c-805a-b378b809665c.mp4

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
