### ISSUE TITLE
[Bug]: Durability - You can't upgrade durability more than max durability

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When trying to upgrade weapon durability, you get the notification that you can't upgrade durability more than max durability. However, not is displayed what max durability is (I figured it's x3 the base). 

1. Click upgrade durability
2. Enter very high number
3. See error message
4. No information about max durability

How to fix : 
-Add a 'max' button
-Make it so any number higher than max = max (ex : 900 is max... if x>=900 then x=900
-When in the upgrade page, display current durability total/max durability instead of current durability / current durability total

![image](https://user-images.githubusercontent.com/8630518/224883555-232dc971-f804-44ac-b36b-998801c3bb1a.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
