### ISSUE TITLE
[Bug]: Adamantite ore - Doesn't show crafts into

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

![image](https://user-images.githubusercontent.com/8630518/224891190-28988b63-5e82-4581-85cc-1a0876af3816.png)
![image](https://user-images.githubusercontent.com/8630518/224891226-e263ab50-998d-4610-b9bc-bc117896d758.png)
![image](https://user-images.githubusercontent.com/8630518/224891365-54258e3c-9521-4f22-bd56-bbdc6658e497.png)

Not sure if the crafting of adamantite bar is enabled yet but the other ore shows the 'crafts into' to help with crafting.

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
