### ISSUE TITLE
[Bug]: The forge - Negative amount of turns

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

Not sure if intended, but I had 4 turns and crafted some titanium bar and styxium bar. Ended up at -1 turn.

![image](https://user-images.githubusercontent.com/8630518/224892057-9678438e-4518-425e-9f39-1ffc9c8c28b9.png)

Titanium bar took 3 turns & Styxium bar took 2 turns.

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
It looks like this definition is missing the adamintite ore from the bar, the other two are right, but its missing the ore

**Comment by Polypup** [comment]
fixed
