### ISSUE TITLE
[Bug]: Crafting - Red Gem highlighted in red even if I have enough resources

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

![image](https://user-images.githubusercontent.com/8630518/224893325-43db4e04-8a8a-498d-9393-dbff6ddd2f43.png)
![image](https://user-images.githubusercontent.com/8630518/224893459-df21e053-ac02-4265-9995-c70822a2f869.png)

If I place my gems on the crafting bench, the tooltip of my blueprint says I don't have enough gems for crafting. When in inventory, it is fine.

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
