### ISSUE TITLE
[Bug]: Gemstone of Health - Does not show the bonus ni

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

![image](https://user-images.githubusercontent.com/8630518/224893719-05447b28-1ffb-47af-8600-b5e5d324cac8.png)
![image](https://user-images.githubusercontent.com/8630518/224893783-0ec1225b-14d9-4d31-917e-2ac9125e2265.png)

Gemstone of health does not show the bonus it gives in the tooltip of the item. 

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Fixed 
<img width="327" alt="Screenshot 2023-03-14 at 12 44 23 AM" src="https://user-images.githubusercontent.com/85349906/224895541-b7aefb1e-0d00-43fa-8b5c-77a6e05d665e.png">
