### ISSUE TITLE
[Bug]: UI Consistency - Crafter's Guild

### ISSUE THREAD

**Issue by BoltTouring** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

Crafter's Guild on the map vs. Crafting Guild in the menu
![image](https://user-images.githubusercontent.com/111258598/225825580-1984bcb5-f357-4da6-b530-1b47be5e8e28.png)
![image](https://user-images.githubusercontent.com/111258598/225825592-b9119916-81f2-41b3-98c1-e6ab4973e25c.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
fixed
