### ISSUE TITLE
[Bug]: Claimed my first consumable item and received a GuideWizard error

### ISSUE THREAD

**Issue by Polypup** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

PolyPup

### What happened?

1. Fought in the plains
2. Earned a healing potion
3. Claimed the item
4. Received the following error

<img width="554" alt="Screenshot 2023-03-20 at 10 20 22 AM" src="https://user-images.githubusercontent.com/85349906/226368852-458d0720-64b8-420e-9cf8-0e9a71cd023b.png">

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed
