### ISSUE TITLE
[Bug]: Events - Potions looted from special events show up in inventory

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

1. Find special event
2. Successful
3. See potion in inventory, but can't use it. (Maybe items too?)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
What are you referring to with a special event?

**Comment by Brainiac1830** [comment]
> 

Old man, loot chest with the spikes.

**Comment by Polypup** [comment]
fixed
