### ISSUE TITLE
[Bug]: DIRECT_HEAL_DISALLOWED

### ISSUE THREAD

**Issue by s1lv3rback** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

kyrpto

### What happened?

![image](https://user-images.githubusercontent.com/121063058/226616917-f1955e3d-4133-4d74-9ba8-099956b6b295.png)

Try to heal and get a DIRECT_HEAL_DISALLOWED message. 

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by s1lv3rback** [comment]
refresh fixed

**Comment by neothon** [comment]
may be the server was restarting when this happened. will try to reproduce it.
