### ISSUE TITLE
[Bug]: have to refresh to see outcome of Bard Song

### ISSUE THREAD

**Issue by s1lv3rback** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

kyrpto

### What happened?

After a bard song, there is no outcome message. You are just taken back to the map. In order to see if you received turns, you need to refresh. 

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed
