### ISSUE TITLE
[Bug]: Resurection - Wrong hero resurected.

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

1. Have 2 dead heroes.
2. Resurrect # 1 
3. Accept transaction
4. Click leave
5. Switch to dead hero # 2
6. Enter healer's hut
7. Wait for transaction to finish
8. UI show hero # 2 healed. Shows the Hero # 1 total hp. When trying to resurrect hero # 1 again, UI breaks

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
Fixed. Can't leave healers hut or swap character till the transaction is completed.
