### ISSUE TITLE
[Bug]: Unable to claim DCAR after completing battle in the plains

### ISSUE THREAD

**Issue by hrothgar2222** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

hrothgar#6370

### What happened?

Completed a first time battle in the plains and was able to claim some equipment/consumable/resource but upon clicking the 'Claim DCAR' button the error message in attached screenshot was thrown.  Unable to proceed with claiming the 1.93 DCAR.
**Note:** This was the very first plains battle done with the character

![image](https://user-images.githubusercontent.com/86222969/204114898-e1011be6-f31a-4a95-9a0a-78bf915eb535.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by hrothgar2222** [comment]
Was able to successfully claim the DCAR upon completing a second battle.  Looks like the system carried forward the reward from the first battle into the second battle as the claim amount was 3.15 DCAR

![image](https://user-images.githubusercontent.com/86222969/204115067-3ae65699-f87e-4e3e-8942-c592467e4cc3.png)

**Comment by neothon** [comment]
Tried reproducing it with an account which had one hero and never played any battle before. Was successfully able to claim. Will try to reproduce with a completely fresh account which never interacted with the game before

**Comment by neothon** [comment]
unable to reproduce it.
