### ISSUE TITLE
[Bug]: Durability in the Deepwoods

### ISSUE THREAD

**Issue by BoltTouring** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

If I have an item equipped and I gather resources in the Deepwood, my item loses durability. If I unequip the item, I can still gather and nothing loses durability.

That mean the most efficient way to gather in the Deepwood is to unequip your weapon, which is weird.
![image](https://user-images.githubusercontent.com/111258598/227699807-12e9f0ad-ccba-4591-b8fc-11d601da3f8c.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Chaney08** [comment]
Fixed by adding a requirement to have an axe equipped to visit the deepwoods, much like how the mines work.
