### ISSUE TITLE
[Bug]: Error in RPC caused server to crash

### ISSUE THREAD

**Issue by Polypup** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

PolyPup

### What happened?

<img width="1000" alt="Screenshot 2022-11-27 at 1 53 58 PM" src="https://user-images.githubusercontent.com/85349906/204154249-dce213b5-51c2-4da1-9232-f92e4e914b1c.png">

Probably just need a try catch in `claim-stash`

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
am looking into this ser
