### ISSUE TITLE
[Bug]: Chat message (issue with time clock)

### ISSUE THREAD

**Issue by WesToStakuj** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

friendly.fire#8915

### What happened?

From first wallet I sent message on chat "One" and showed time was 10hours ago. 
One second later I wrote "Two" and both massages was shows as wrote 10hours ago on that wallet/browser. 
Than I log in to another wallet&browser and wrote "3 and 4".

First wallet now shows me chat with all wrong time for all 3messages
![Screenshot_20221128_062153](https://user-images.githubusercontent.com/119375694/204415498-3b1a56ba-d23b-4732-b589-96ff942a2afd.png)

Second wallet now shows me proper time for last two massages but not for older.
![Screenshot_20221128_062221](https://user-images.githubusercontent.com/119375694/204415496-a8d48d0f-1305-4e71-ba54-6e448c432324.png)

Presented data on both wallets its not same.

### What browsers are you seeing the problem on?

Chrome, Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed and pushed
