### ISSUE TITLE
[Bug]: Chaotic items - break down improper data

### ISSUE THREAD

**Issue by WesToStakuj** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

friendly.fire#8915

### What happened?

I noticed for all items in my wallet with Chaotic element the break down resources are pulled from previous reading but not from correct one. 

First for example I check the crafting menu and break down resources on any random item from my wallet (in this case its shield):
![Screenshot_20221128_065107](https://user-images.githubusercontent.com/119375694/204418774-ef069d80-d17b-4406-aae2-a8461d582f2b.png)
So it shows me if I break it than I will receive some wood in return what is correct.

Now I going to do same for any of item with Chaotic element and it will pull break down resources from the shield not from the item what in this case is chaotic belt:
![Screenshot_20221128_065350](https://user-images.githubusercontent.com/119375694/204419144-1e5ecd75-45b4-406c-a98f-6d0871e18f04.png)
Shows me wood what is incorrect. 

![Screenshot_20221128_065634](https://user-images.githubusercontent.com/119375694/204419673-01033499-3302-4c77-9e20-37df53b67387.png)
![Screenshot_20221128_065706](https://user-images.githubusercontent.com/119375694/204419689-ec230317-bbd5-4a91-9d30-ffb68841edc5.png)
Another check first on ice pants than again on the chaotic belt and pants part are displayed what isnt correct.

It happens on both wallets on both browsers on all chaotic items what I have (chest/belt/brace/hood)
![Screenshot_20221128_070005](https://user-images.githubusercontent.com/119375694/204420074-29434402-a9ed-434a-bbaa-8460c0da87f9.png)
![Screenshot_20221128_070032](https://user-images.githubusercontent.com/119375694/204420084-ff4019d9-ec65-4fa7-a2b4-cc6a58610d41.png)

### What browsers are you seeing the problem on?

Chrome, Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Resolved and pushed

**Comment by SivDraconis** [comment]
Confirmed fixed
