### ISSUE TITLE
[Bug]: Mining - No pickaxe or skill required.

### ISSUE THREAD

**Issue by WesToStakuj** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#51]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Contact Details

friendly.fire#8915

### What happened?

I abuse mining system and feel like something here is bugged and should be check if we want to let it go as is.

I have only one heroNFT with great skill of gathering and only this one wear pickaxe. The rest the best what can mine is coal and dont wear pickaxe.
![Screenshot_20221128_071027](https://user-images.githubusercontent.com/119375694/204422219-aa7d3129-10a1-4614-ab55-2bba59c3ebf3.png)

I using my gatherer to get in to the mine. He need just one action point what wont be consumed to give access to the mine to the rest because from now I am in the mine and I am able to switch between heroNTFs. I am looking for interesting me resource (I can click hundreds of times search again with no cost ?!)
![Screenshot_20221128_071140](https://user-images.githubusercontent.com/119375694/204422541-97af68d5-4298-4e49-bd2d-a02d66457f2b.png)

Once I found resources what I want than I stop searching for others and do switch to another unskilled heroNFT with no pickaxe to use his action point and dig resource.
![Screenshot_20221128_071231](https://user-images.githubusercontent.com/119375694/204422795-bf5fca5d-20cf-4626-aa3c-76942ea5c857.png)

Than I switch heroNFT again to the gatherer to keep searching.
![Screenshot_20221128_071253](https://user-images.githubusercontent.com/119375694/204422893-1eb4feef-476d-43ac-8059-9d791f65b813.png)

And keep spending all my action point on all heroesNFTs doesn't matter what their skill and equipment are.
![Screenshot_20221128_071317](https://user-images.githubusercontent.com/119375694/204423089-e31692a3-ffcb-4afd-849c-dc7bf4e10774.png)

### What browsers are you seeing the problem on?

Chrome, Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Resolved and opened PR
