### ISSUE TITLE
[Bug]: UI glitch during fight after cancelled tx

### ISSUE THREAD

**Issue by WesToStakuj** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

friendly.fire#8915

### What happened?

![Screenshot 2022-11-29 043901](https://user-images.githubusercontent.com/119375694/204520535-b5664fbc-ca50-4cba-a4bd-54facd4b84d5.png)
I started fight with any enemy and have 3 "icons" options to click (Fight/BagToSeePotions/Run). 
To play I use keyboard (press "1" to Fight etc.) but this time I press number "4"

![Screenshot 2022-11-29 043951](https://user-images.githubusercontent.com/119375694/204521284-6fde3b18-850f-41f4-9c77-d8e72735ea23.png)
It popup me tx to approve and I believe its a use one of potions but I cancel it and back to the game. 3 icons are replaced at this time by one moving blue circle

![Screenshot 2022-11-29 044025](https://user-images.githubusercontent.com/119375694/204521641-384b4327-555a-4b83-9b3a-4d65384f7bc4.png)
Transaction its closed but I don't see my 3 icons instead of that I have only that blue circle.. Don't see my bag or run.

![Screenshot 2022-11-29 044103](https://user-images.githubusercontent.com/119375694/204521867-03649161-3665-403b-92eb-626d6d6bc2a2.png)
The way out of this situation its to use keyboard and press "1" to fight and beat enemy. "3" isn't a run out. Once fight is over and you go to the plains to fight another the blue circle will shows up and to clean UI you need to relog on wallet. 

Edit: When even in that next fight you click "5" it will use great potion and give back you heath and bring back the UI without relogging. But the transaction on potion need to be approved not cancelled. 

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed and pushed
