### ISSUE TITLE
[Improvement]: Fight Exp rewarded to correct hero 

### ISSUE THREAD

**Issue by Polypup** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#55]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Contact Details

PolyPup

### What happened?

Per hit in fight exp/loot distribution, so swapping heros, the one that did the most dmg gets the most exp, the luck is generated from them too

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
@sam-thewise would you like the exp split between each hero according to total damage done by each hero.

Example: 

Total Damage = 10
Total Exp = 100

Character 1 = 1 Damage = 10 Exp
Character 2 = 5 Damage = 50 Exp
Character 3 = 4 Damage = 40 Exp

Or the player with the most damage receives the exp.

**Comment by sam-thewise** [comment]
Yes that's right - it's distributed as above :) - not the player with the most damage

**Comment by sam-thewise** [comment]
We also need to calculate luck/loot by doing an average of the heroes who participated and the dmg they did too

**Comment by Polypup** [comment]
Perfect, I'll get this done asap!

**Comment by Polypup** [comment]
Completed
