### ISSUE TITLE
[Bug]: Add proper ingredients to deepwood for crafting potions

### ISSUE THREAD

**Issue by Polypup** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

PolyPup

### What happened?

Correct ingredients for deepwood for crafting potions

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
Added new potions, magic skill requirement and new ingredients for proper crafting
