### ISSUE TITLE
[Bug]: Resting at Inn and switching characters

### ISSUE THREAD

**Issue by SivDraconis** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

- Rest at the Inn. 
- Switch characters in upper left
- UI breaks and turns are not refreshed for character that started the transaction
- Turns are correct on browser refresh

https://www.twitch.tv/videos/1667835423

![image](https://user-images.githubusercontent.com/111258598/205188956-43cb84bc-b0d4-45c9-a71a-7bb8c6c0bcc7.png)

### Relevant log output / error message

```shell
See above
```

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Thanks for the video, it really helps debug. I'll get this fixed up right away

**Comment by Polypup** [comment]
Fixed and pushed. 

- checked for correct heroId on api
- watch for character switch in Inn

**Comment by SivDraconis** [comment]
Confirmed fixed - nice one!
