### ISSUE TITLE
[Bug]: Start a battle with ongoing healing transaction

### ISSUE THREAD

**Issue by Lazerthelazy** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Lazer_the_lazy#0343

### What happened?

Started a battle before transaction of "Get a room" went throuh. During fight the Wild Boar Inn window popped up. The healing part worked but the game was broken after leaving the inn. 
After refresh I rejoined the battle but without an equipped weapon.

### What browsers are you seeing the problem on?

Firefox

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
Fixed by disabling leave buttons till transactions are complete. For both healer's hut and inn

**Comment by SivDraconis** [comment]
Confirmed. I can't leave :D

**Comment by SivDraconis** [comment]
@Polypup - if I start a healing transaction then refresh then go to battle the healing transaction does not go through. Users *shouldn't* do this but it feels bad to lose that $.

**Comment by SivDraconis** [comment]
I was able to break the Healer doing the above: https://www.twitch.tv/videos/1669627845
