### ISSUE TITLE
[Bug]: Background for Deepwoods is currently the background for the Mines 

### ISSUE THREAD

**Issue by 0xGlen** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Replace Deepwoods background with the correct one

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed
