### ISSUE TITLE
[Enhancement]: By default select the previously selected hero as active on refresh

### ISSUE THREAD

**Issue by neothon** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#71]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What happened?

On refreshing the game, the default hero sequence is applied and the active hero gets changed. Implement solution so that always the active hero is by default active on refresh

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by SivDraconis** [comment]
Confirmed fixed - I'm seeing the Deepwood background.

**Comment by neothon** [comment]
Completed
