### ISSUE TITLE
[Bug]: Character selection disappears in Crafters' Guild

### ISSUE THREAD

**Issue by SivDraconis** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

I can't switch heroes while in the Crafter's Guild
![image](https://user-images.githubusercontent.com/111258598/205465291-350d9cef-d7ee-45a8-91d9-1684a26e98db.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by SivDraconis** [comment]
Also - when I add, remove and re-add a receipe the UI on the right disappeared and I could not leave the guild.

**Comment by Polypup** [comment]
Fixed, waiting on bigger merge to go through and then will push this through.
