### ISSUE TITLE
[Bug]: Trying to buy something in the marketplace when I don't have enough DCAU

### ISSUE THREAD

**Issue by SivDraconis** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

When I click "buy" on an item but do not have enough DCAU, it just spins.

Around minute 44 in today's stream

![image](https://user-images.githubusercontent.com/111258598/205465746-51428726-d51e-4df2-9b1c-cd58686b96f7.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed
