### ISSUE TITLE
[Enhancement]: Add a button that allows player to buy DCAU/DCAR when player has insufficient amount

### ISSUE THREAD

**Issue by 0xGlen** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#74]
e.g. at the Healer's Hut, add a button to "Buy DCAU" that appears when there is insufficient DCAU. Could be a link to the TJ Dex: https://traderjoexyz.com/trade?inputCurrency=AVAX&outputCurrency=0x100cc3a819dd3e8573fd2e46d1e66ee866068f30#/

**Comment by neothon** [comment]
This is already there. If user doesn’t have enough dcau, the heal button converts into a buy button. At present it’s just a button but on main net will point to actual partner dex link

**Comment by neothon** [comment]
![image](https://user-images.githubusercontent.com/89765091/205478116-e68636fd-4dcb-4890-a786-177af7f0777d.png)

fixed. The buy button wasn't visible earlier .
