### ISSUE TITLE
[Bug]: 'You have used a potion' triggered too early while on global map

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

When on the global map, if you use a potion it will trigger the prompt 'You have used a potion' right away. Even if you have not completed the transaction.

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed. can only use keyboard shortcuts in combat for now.

**Comment by Brainiac1830** [comment]
> fixed. can only use keyboard shortcuts in combat for now.

The issue is not that we can use keyboard shortcuts, but the fact that the potion success prompt is shown before the transaction is successful. 

I triggered this out of combat by clicking on the item bar.

![image](https://user-images.githubusercontent.com/8630518/206077965-56b75b45-3185-4da1-97d8-12567758ea39.png)
