### ISSUE TITLE
[Enhancement]: Dashboard to track vital backend infrastructure 

### ISSUE THREAD

**Issue by Polypup** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

PolyPup

### What happened?

We need to track the following:

- balance of dev wallet to make transactions - we just ran out of funds and api is erroring out
- ping rpc
- ping websockets rpc

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
Added whitelisted address to show avax balance, rpc and wsrps statuses 
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/89765091/203656877-2bf997b7-bb64-4b29-a551-ce7ae98382d1.png">
