### ISSUE TITLE
[Enhancement]: Add a minimap 

### ISSUE THREAD

**Issue by 0xGlen** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#80]
Can be hard to navigate across the game map on a small screen, especially as the game map grows larger as more locations are added. Add a minimap to the top right corner of the UI showing current view location relative to the entire map.

**Comment by 0xGlen** [comment]
Good idea Sam!

**Comment by neothon** [comment]
added quick access minimap elements. Minimap will be added in v1.1
