### ISSUE TITLE
[Bug]: Experience Bar overloaded

### ISSUE THREAD

**Issue by WesToStakuj** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I had one of my low level HeroNFT gain a lot experience at once (more as two levels) so my experience bar was close to make a hole on right side of screen. After I set first 10points for skills than to set second 10 skill points I needed refresh game 
![Screenshot 2022-12-05 074302](https://user-images.githubusercontent.com/119375694/205913451-c1a1815b-7d8a-47ba-957d-8751d204fbd1.png)

### What browsers are you seeing the problem on?

Brave

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
fixed
