### ISSUE TITLE
[Bug]: Full light in forest during night.

### ISSUE THREAD

**Issue by WesToStakuj** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

New background in deepwood its too bright when in game is night. 
![Screenshot 2022-12-06 053840](https://user-images.githubusercontent.com/119375694/205915084-b03e212a-2841-4a7a-b194-09aaf023f33d.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by neothon** [comment]
added night version of deepwood
