### ISSUE TITLE
[Bug]: Helth restore after death

### ISSUE THREAD

**Issue by WesToStakuj** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2022-12-05 083113](https://user-images.githubusercontent.com/119375694/205915332-aa6e57e9-ab28-40be-a40b-670761a81744.png)

During battle I was low on health so I used potion and confirmed transaction. I didn't wait to the approve on transaction and hit one more time enemy and his hit back just kill me. I went dead but than transaction got approved and I restored some heath but needed resurrected by character anyway. There should be disable option to hit enemy during approval on potion same as you did when you cannot leave holiday inn when during sleep transaction.

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Brainiac1830** [comment]
Mentioned in issue #78

**Comment by neothon** [comment]
Hey, this should be fixed. Can you try again?

**Comment by neothon** [comment]
Let me know if this isn't resolved and will reopen again
