### ISSUE TITLE
[Enhancement]: Add grouping in equipment 

### ISSUE THREAD

**Issue by WesToStakuj** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

friendly.fire#8915

### What happened?

Please add some kind of grouping t the inventory based on category and/or by rarity.

I own many NFT items and wish to keep them not break right away but after some time my inventory is too big and I spent too much time for looking on items. It will help and save my time if I can group them and have all hat separated from pants etc. also could be awesome if I could also group them base on skill for example items with bonus to crafting together in order from biggest bonus to lowest etc.

![Screenshot 2022-12-06 065612](https://user-images.githubusercontent.com/119375694/205932003-cdd6100c-de40-4148-859d-f4208165bae1.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
Approved and merged, nice work @Polypup
