### ISSUE TITLE
[Enhancement]: Allow to remove/change price on item listed on marketplace.

### ISSUE THREAD

**Issue by WesToStakuj** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

friendly.fire#8915

### What happened?

I set some items on sale. After one week its still there and I would like to change price or delist them but is impossible. 
![Screenshot 2022-12-06 075908](https://user-images.githubusercontent.com/119375694/205946702-5653c733-3294-4300-86b3-1867bf8dd1ac.png)

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by SivDraconis** [comment]
My items on the marketplace have a "cancel listing" button. Are you connected to the right account and then clicking "my listings?"

**Comment by WesToStakuj** [comment]
Close I didn't noticed tab with "My listings"
