### ISSUE TITLE
[Bug]: Empty Blueprints on sale on market.

### ISSUE THREAD

**Issue by WesToStakuj** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

friendly.fire#8915

### What happened?

I had empty blueprints for bandages in wallet and was able to set them on market. The problem is market don't
![Screenshot 2022-12-06 075908](https://user-images.githubusercontent.com/119375694/205947417-67880810-1df7-444f-8b51-4927e89e14b1.png)
![Screenshot 2022-12-06 052440](https://user-images.githubusercontent.com/119375694/205947477-b6942f5d-5db9-4550-8243-92d1cd1ead3e.png)
![Screenshot 2022-12-06 070727](https://user-images.githubusercontent.com/119375694/205947482-261cbb19-36a0-4df5-94dc-a66617fd6db5.png)
 show how many crafts left so someone will be disappointed. Please add option at least to see how many crafts left on blueprints what are listed on market.

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Brainiac1830** [comment]
I think the blueprint should simply be burned when it reaches 0 stacks. Unless there is a way to refill charges for a certain cost?

**Comment by Polypup** [comment]
- Added crafts remaining stat to marketplace for blueprints.
- No longer allowing blueprints with 0 crafts remaining to be sold
- Removed current items with 0 crafts remaining
- Removed blueprints from inventory when no crafts remain
