### ISSUE TITLE
[Bug]: Hotkey in combat

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

There is a new bug that appeared while using hotkeys in combat. Whenever I pressed '1' before it would use my weapon. But now it uses some healing items and prompts a transaction. 

Here's what is being used when pressing the hotkey.

1; Master healing potion
2; Legendary healing potion
3; Healing Potion
4; Greater healing potion
5+; nothing happens

The problem seems to be that pressing an hotkey now disregards the real hotkey '1' and '2' and the new '1' is actually '3'

![image](https://user-images.githubusercontent.com/8630518/206083823-cc3bc866-24de-4fed-88b6-b61a4a14582c.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by WesToStakuj** [comment]
That's a big issue for me to. Before I was abusing "1" during fight now as Brainiac mentioned it brings transaction to the potion and treat me as I am inside the potions bag not in menu fight/bag/run.

**Comment by neothon** [comment]
This is fixed now. With the new combat button system, it wasn't strictly following the hotbar style hence it was a bit different. I ensured it follows the hotbar keys now 👍🏼😊

**Comment by neothon** [comment]
do check and comment here.
