### ISSUE TITLE
:BUG: Issue #78 still not resolved

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#93]
> fixed

Not fixed, can still click on **auto play** to continue fighting while there's a potion transaction in process.

_Originally posted by @Brainiac1830 in https://github.com/Dragon-Crypto-Gaming/DCG-Bug-Reporter/issues/78#issuecomment-1340336553_

**Comment by neothon** [comment]
oops! I was focusing on disabling use of potion via keyboard while fighting. Missed this! Thanks. Disabled autoplay button while consuming.
