### ISSUE TITLE
[Bug]: Notification timestamps doesn't update while playing

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

The notification timestamps does not update in real time while playing the game. It will always say **a few seconds ago** until you refresh the page, even blockchain transactions does not update this.

![image](https://user-images.githubusercontent.com/8630518/206093075-4fb7e1f9-7b9e-4926-8646-e0539eaa6fdb.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Brainiac1830** [comment]
Here's a video for reference.
https://www.youtube.com/watch?v=ahSWEPg1E4c&feature=youtu.be

**Comment by neothon** [comment]
fixed
