### ISSUE TITLE
[Bug]: NFT Approval in Forge isn't working

### ISSUE THREAD

**Issue by SivDraconis** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Siv

### What happened?

I approved the NFT contract to forge, but I am still unable to forge. Refreshing allows the forging to continue.
<img width="1512" alt="Screen Shot 2022-12-08 at 9 42 29 am" src="https://user-images.githubusercontent.com/111258598/206321546-9e16ae68-2cff-4844-a673-aeb81ec24c99.png">

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Added loading to the approval mechanism.
