### ISSUE TITLE
[Bug]: Daily quest doesn't show up until you refresh the game.

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#98]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

I have had the game opened for a while and only got prompted about the daily quest when I did a page refresh.

Should pop up as soon as it's ready!

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment]
Daily quests show up during character switch and during login. I added the check for this more frequently and made for a bad user experience as it was popping up when I was trying to do something else.
