### ISSUE TITLE
[Bug]: +Gathering item bonus not working properly.

### ISSUE THREAD

**Issue by Brainiac1830** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Brainiac#0847

### What happened?

I have a character with **gathering** skill of **19** > 1(character) +18(gear)

I'm unable to find anything else than _Iron ore_ in the mines. I should be able to find _Coal_ (10) and _Bones_ (15).

Also, unable to find Enchanted Lesser stones of .... (95) at Gathering skill 103 (87+16)

![image](https://user-images.githubusercontent.com/8630518/206369223-c5ff44b7-f513-4117-999c-dfd9da9eb10d.png)

### What browsers are you seeing the problem on?

Chrome

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment]
We're reviewing this code now, then it'll be on the test server

**Comment by sam-thewise** [comment]
This is fixed and merged
